### ISSUE TITLE
Support tagging by user_id and email

### ISSUE THREAD

**Issue by dehora** [intercom/intercom-ruby#102]
`Intercom::Tag.tag_users` only accepts the `id` field for a user. This means users typically have to be fetched before they can be tagged. We should surface the tag by email and user_id options that are available in the HTTP API.

**Comment by maartenvanvliet** [comment]
At the minimum the docs should be updated to mention that tagging by email and user_id is not possible in the expected fashion. Only through the method in the aforementioned mentioned issue #120

**Comment by josler** [comment]
this is addressed in v3: https://github.com/intercom/intercom-ruby/pull/159
