### ISSUE TITLE
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Server Error and http_code: '500'. Please contact Intercom with these details.

### ISSUE THREAD

**Issue by mustela** [intercom/intercom-ruby#132]
I'm having that exception when I try to update an existing user, the code is really simple the the error doesn't tell me anything.

``` ruby
user = Intercom::User.find(user_id: xxxxxxx)
    user.email = 'Emilino'
    user.name = 'Florez'
    user.save
```

Any clue?

**Comment by constantm** [comment]
Just had the same issue with version 2.4.3 of the gem - sent you a mail @josler.

**Comment by GolfyMcG** [comment]
@josler I'm sure it's probably more in line with the vision of the company to do all of your support through Intercom but in this example (and others on GIthub) it would probably make sense to log support on Github since people (like me) will Google for the solution and find nothing but you saying to contact you via Intercom which isn't the M.O. for most web development. Just food for thought.

**Comment by prokizzle** [comment]
+1

**Comment by fullofcaffeine** [comment]
+1

**Comment by jgadbois** [comment]
I'm getting this error as well

**Comment by sunild** [comment]
+1

**Comment by alexboots** [comment]
+1

**Comment by prokizzle** [comment]
My general understanding is that most of these errors are actually 422 errors. Like setting an attribute that's really a reserved word or reserved attribute, or setting an attribute that should really be a custom attribute.

**Comment by jgadbois** [comment]
That was true in my case

**Comment by prokizzle** [comment]
My solution - before trying to modify a user object, check to see if the attributes you're setting are reserved words first. You will probably have to maintain an array manually (I do).

```ruby
    def self.apply_attributes(user, _user, attributes, reserved = user_reserved)
        attributes.each do |key, value|
            if reserved.include? key
                user.send("#{key}=", value)
                next
            end
            user.custom_attributes[key] = value
        end
        user.custom_attributes.delete_if do |key, value|
            reserved.include?(key)
        end
        save(user, _user)
    end

    def self.user_reserved
        [
            :name, 'name',
            :type, 'type',
            :title, 'title',
            :company, 'company',
            :city, 'city',
            :job_title, 'job_title',
        ]
    end

    def self.company_reserved
        [
            'plan', :plan,
            'name', :name,
            'id', :id,
            'company_id', :id,
            'monthly_spend', :monthly_spend
        ]
    end
```

**Comment by tute** [comment]
I see this error while running in development with dummy secret keys. How do I disable Intercom in development?

**Comment by sinclair** [comment]
Receiving this error today when calling, ```Intercom::Message.create({message_type: 'inapp', subject: "...", body: msg, from: from})```
Version: `intercom-2.2.4`

**Comment by aishmita-aggarwal** [comment]
Received this error today which says:

The error of type '' is not recognized. It occurred with the message: Server Error and http_code: '500'

when called: client.users.create

Version: intercom-3.5.12

**Comment by aditya9026** [comment]
getting the same error when fetching the user from intercom:
intercom (3.5.23)
intercom-rails (0.3.8)

**Comment by gvraams** [comment]
I'm facing a similar issue but clearly different error message. More details are given below

`Intercom::UnexpectedError: The error of type ‘’ is not recognized. It occurred with the message: Company already exists. and http_code: ‘400’. Please contact Intercom with these details`

intercom-3.5.25:

`IntercomClient.users.create(
  user_id: @account_member.user_id,
  companies: [{
    company_id: @account_member.company_id,
  }],
)`

Stack trace is as follows:

`/home/deploy/.bundler/germ_io_api/ruby/2.2.0/gems/intercom-3.5.25/lib/intercom/request.rb:178:in 'raise_application_errors_on_failure'
/home/deploy/.bundler/germ_io_api/ruby/2.2.0/gems/intercom-3.5.25/lib/intercom/request.rb:105:in 'parse_body'
/home/deploy/.bundler/germ_io_api/ruby/2.2.0/gems/intercom-3.5.25/lib/intercom/request.rb:72:in 'block in execute'
/home/deploy/.bundler/germ_io_api/ruby/2.2.0/gems/intercom-3.5.25/lib/intercom/request.rb:67:in 'execute'
/home/deploy/.bundler/germ_io_api/ruby/2.2.0/gems/intercom-3.5.25/lib/intercom/client.rb:113:in 'execute_request'
/home/deploy/.bundler/germ_io_api/ruby/2.2.0/gems/intercom-3.5.25/lib/intercom/client.rb:93:in 'post'
/home/deploy/.bundler/germ_io_api/ruby/2.2.0/gems/intercom-3.5.25/lib/intercom/api_operations/save.rb:27:in 'save'
/home/deploy/.bundler/germ_io_api/ruby/2.2.0/gems/intercom-3.5.25/lib/intercom/api_operations/save.rb:19:in 'create'
...intercom_account_member_worker.rb:8:in 'perform'`

**Comment by leandrocastro** [comment]
The same error here:
Intercom :: UnexpectedError: The error of type '' is not recognized. It occurred with the message: Server Error and http_code: '500'. Please contact Intercom with these details.

Gem version: 3.8
Ruby 2.5
Rails 6.0
