### ISSUE TITLE
Testing and intercom-ruby

### ISSUE THREAD

**Issue by constantm** [intercom/intercom-ruby#137]
Is there any good way to test your application whilst using intercom-ruby, without disabling it completely in the test environment (which I don't want to do for obvious reasons)?

It would be great if there was some way to have a separate sandbox area in Intercom for data created through tests. The only way I can see this working at the moment is to create a separate dummy Intercom account to use for testing?

**Comment by jonathanheron** [comment]
@constantm Your app can have a *test version*, with its own app id code. Here are the details of [how to set it up](http://docs.intercom.io/configuring-Intercom/creating-a-test-version-of-intercom).

Cheers,
Jonathan

**Comment by constantm** [comment]
Awesome, thanks! My Googling attempts didn't bring that up.

**Comment by constantm** [comment]
On another point - Along with the app_id, I needed to also change my Intercom.app_api_key to that of the test version for the Ruby client. The docs doesn't say this.

**Comment by tannerhallman** [comment]
It's advantageous for speed to not actually hit an external source during your tests. It also creates a dependency on a network connection for tests (not the end of the world) to run which ultimately makes it more fragile . Has anyone found a good way to mock this?

**Comment by tannerhallman** [comment]
I also run into conflicting user id's between my tests so I guess I need to clear intercom after each run?
