### ISSUE TITLE
User Avatar: bad 'avatar' parameter

### ISSUE THREAD

**Issue by F4Ke** [intercom/intercom-ruby#138]
According to http://doc.intercom.io/api/#users
I try to add an avatar to my users when they update their profile.

But, when I save tu Intercom User, I have this error : 'bad 'avatar' parameter'

In my update method I call my Intercom update :

      user.avatar = {
        :type => "avatar",
        :image_url => u.avatar.to_s
      }

I also tried 

      # user.avatar.type = "avatar"
      # user.avatar.image_url = u.avatar.to_s

When I

      user.save

the error comes out. (Only in the first case, in the second nothing append and image_url stays at nil)
What I've done wrong ?

**Comment by josler** [comment]
Hi @F4Ke,

It's currently not possible to set an Avatar manually within Intercom - the fields supported by the API for create and update operations on a User are detailed here: http://doc.intercom.io/api/#create-or-update-user.

Thanks!

**Comment by lemboy** [comment]
Hello,

I see **avatar** field here:
[https://developers.intercom.com/reference#create-or-update-user](https://developers.intercom.com/reference#create-or-update-user)

```
The table below shows the fields you can create or update for a user -
...
avatar The user's avatar image url
...
```

But I can't create User with avatar. It is possible now?

Thanks.

**Comment by lemboy** [comment]
It works!

> An avatar image URL. note: the image url needs to be https.

So now we can:

`intercom.users.create(user_id: 12345, email: 'example@mail.com', name: 'Jack Frost', avatar: { type: 'avatar', image_url: 'https://example.com/avatar.png' })`

or

`user.avatar = { type: 'avatar', image_url: 'https://example.com/avatar.png' }`

**Comment by sethukarthik** [comment]
Thanks lemboy it is working fine for me.

**Comment by antonholmquist** [comment]
I failed to set the avatar and asked their support for help, this was their reply:

> You're right, there's times when this is possible, but officially we don't support setting avatars, it's more like a lucky accident that it's possible at the moment. However many people do want to be able to do this and our product team are considering if we will support this in the future 😄

**Comment by antonholmquist** [comment]
Is this still not supported? I can't get it to work.

**Comment by thewheat** [comment]
@antonholmquist using the syntax shared in https://github.com/intercom/intercom-ruby/issues/138#issuecomment-259625082 I was able to update a record on my end.

I used this
```
intercom.users.create(
  user_id: 13,
  avatar: { type: 'avatar', image_url: 'https://avatars2.githubusercontent.com/u/505089?s=88&v=4' }
)
```

If you're having issues feel free to email team@intercom.com / send us a messages via the Intercom messenger and let us know your code and we can dig into it 👍

**Comment by derekyle** [comment]
I haven't been able to get mine to work and got a similar answer from support that it wasn't supported. Despite the fact that the documentation mentions avatar updates. Intercom seems to prefer to stick with the strangely inaccurate paid service they are using to randomly scrape for profile pics. My own avatar as a customer in intercom comes up as the logo for the university I graduated from a decade ago. Not sure why the "Full Contact" service isn't just taking the profile pic only.

The intercom team seems uninterested in fixing some of these little bugs or deficiencies. Another one being just displaying City, Country for the detected location of intercom leads and customers. We are talking literally 10 minutes of coding. The state is probably already provided by the location API, just stick it in the output string.

"Oh, this customer is in 'Springfield, United States', well that's helpful.
