### ISSUE TITLE
 warning: circular argument reference - application_error_code

### ISSUE THREAD

**Issue by Neku** [intercom/intercom-ruby#143]
I get this error /Users/Simone/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/intercom-2.4.2/lib/intercom/errors.rb:6: warning: circular argument reference - application_error_code
with ruby 2.2.0

**Comment by josler** [comment]
This was fixed with version 2.4.3 and later of the gem. Thanks
