### ISSUE TITLE
How to use Intercom.rate_limit_details ?

### ISSUE THREAD

**Issue by hongmingChm** [intercom/intercom-ruby#147]
Hi, I tried to run
Intercom.rate_limit_details
in the console, but for somehow it returns empty hash {}

Is there anything I do wrong from my side?
 And is there a way we can check the call limit from intercom web app?

Thanks in advance.

**Comment by josler** [comment]
Hi @hongmingChm.

Have you tried making a call to the API before checking the rate limit? The rate limit details are returned as part of each request.

**Comment by hongmingChm** [comment]
Hi Josler,

Got it already. Thanks for the quick reply.

Didn't know I need to make a request before I can get the rate limit.
