### ISSUE TITLE
Problem with type attribute on event metadata

### ISSUE THREAD

**Issue by Draiken** [intercom/intercom-ruby#153]
Hi there!

I found a problem when creating an event with the `type` attribute on the metadata hash. This only occurs when the hash uses a `type` string key, not when it's symbolized.

The event we tried creating was something like:

    {
      "user_id" => 582731,
      "event_name" => "Played Tournament",
      "metadata" => {
        "type" => "S&G",
        "poker_variation" => "NL Holdem"
      },
      "created_at" => 1430392843
    }

And it generated the following error:

    NameError: wrong constant name S&g

The stacktrace led us to the `lib/intercom/traits/api_resource.rb` where it checks if we have a type on a custom attribute and tries to constantize it.

I don't believe this is intended (as it doesn't show anywhere in the docs a restriction to metadata attribute names), so we're temporarily changing the string key to a symbol.

**Comment by bobjflong** [comment]
Hi @Draiken 

Thanks for the report. Are those Events being created in your Intercom app despite this error? This version of the gem reserves the field `type` for identifying API resources. I'd recommend using another field like `tournament_type`. I will add some documentation explaining this issue for now.

Bob

**Comment by Draiken** [comment]
I'll change the attribute name then.

Regarding the event creation, when the `type` is a string, it doesn't work, but simbolizing it seems to do the trick. Since it's not a `HashWithIndifferentAccess` it doesn't find the `type` key and doesn't try to constantize it's value.
