### ISSUE TITLE
Warning: circular argument reference - client

### ISSUE THREAD

**Issue by hpoydar** [intercom/intercom-ruby#161]
Ruby 2.2.2

`/app/vendor/bundle/ruby/2.2.0/gems/intercom-3.0.0/lib/intercom/client_collection_proxy.rb:9: warning: circular argument reference - client`

**Comment by josler** [comment]
Thanks! This should be fixed with 3.0.1.

**Comment by hpoydar** [comment]
:( `intercom-3.0.1/lib/intercom/client_collection_proxy.rb:9: warning: circular argument reference - client`

**Comment by josler** [comment]
Sorry about that - wrong .gem pushed  :( - 3.0.2 has the fix now
