### ISSUE TITLE
README has wrong delete DSL?

### ISSUE THREAD

**Issue by brianhempel** [intercom/intercom-ruby#163]
The README says you can delete a user with:

```ruby
# Delete a user
deleted_user = intercom.users.find(:id => "1").delete
```

But reading the tests and the code, it looks like the only supported method is:

```ruby
user = intercom.users.find(:id => "1")
intercom.users.delete(user)
```

**Comment by josler** [comment]
Oops! Thanks for pointing that out, I've fixed the README now.
