### ISSUE TITLE
500 Error on user create

### ISSUE THREAD

**Issue by rossgeesman** [intercom/intercom-ruby#164]
We tried updating our user data (roughly 15k records) with a rake task and received a large number of 500 errors with the following message:

`Failed to update user with FFID '45168'. Error message: 'The error of type '' is not recognized. It occurred with the message: Server Error and http_code: '500'. Please contact Intercom with these details.`

Only about 5000 users updated and the rest had errors. The rake task looks something like this:

```
User.find_each(batch_size: 100) do |user|
      INTERCOM_API.users.create(
      email: user.email,
      name: user.name,
      user_id: user.id,
      signed_up_at: user.created_at, 
      custom_attributes: {
      custom_attributes: { #a bunch of custom user attributes
      :foo => foo.bar
      })
```
Any assistance would be much appreciated!

**Comment by dehora** [comment]
Thanks @rossgeesman - this looks like a server issue rather than a client one - I've contacted you on Intercom as I think it's been fixed.
