### ISSUE TITLE
Can't use with JRuby

### ISSUE THREAD

**Issue by sporkd** [intercom/intercom-ruby#166]
Hi. Just wondering what features of Ruby 2.1 are being used that requires locking the gemspec to it?  We're using the latest stable version of Jruby which is only compatible with 1.9.3, so it seems we can't use this gem. Was hoping for an easy integration with Intercom.

**Comment by bobjflong** [comment]
Hi @sporkd thanks for getting in touch. We use some useful features of Ruby 2 like named keyword arguments. I'm looking forward to a new stable release of JRuby!

You could try using version 2 of the gem: https://github.com/intercom/intercom-ruby/blob/c6b972e5e639484d6e75b0f5725e3231c8a5d928/README.md

**Comment by sporkd** [comment]
Thanks @bobjflong! Didn't realize there was a 1.9.3 compatible release in the not so distant past. Will give it a try.
