### ISSUE TITLE
Question:  Event fetch api

### ISSUE THREAD

**Issue by kyprifog** [intercom/intercom-ruby#167]
Quick question.  Does the api development have anything planned for adding the capability to fetch events?  If so do you have an idea of when that might occur?  Are there other ways to glean events from other endpoints?  

Thanks!

Kyle

**Comment by josler** [comment]
Hi @kyprifog - nothing planned for the immediate future; there's other product features we'd like to implement with events that would supersede any API work we did now.

Thanks
