### ISSUE TITLE
Gem does not allow global configuration

### ISSUE THREAD

**Issue by Jaco-Pretorius** [intercom/intercom-ruby#175]
We use the intercom gem in a number of places, which means we need to create a client every time *and* specify the api_key *every* time.  This seems strange - could we rather have a global configuration block where we can specify the app and api key and then Intercom::Client.new would just default to those keys?

**Comment by josler** [comment]
Hi @Jaco-Pretorius 

This was a conscious decision in order to make using the Intercom gem in a multi-threaded environment possible. To get what you're after you could use a globally available method that reads your own global configuration and returns a configured client. In Rails you could do this in a config/initializer file, for example.

Thanks!

**Comment by Jaco-Pretorius** [comment]
@josler How does what I'm proposing exclude usage in a multi-threaded environment?  I'm simply proposing that the `Intercom::Client` would read the API keys from some global configuration when it is instantiated.

**Comment by josler** [comment]
Sorry, in a mutli-threaded and multi-tenant environment; for example for applications that integrate with Intercom, they'd need to switch credentials.

See https://github.com/intercom/intercom-ruby/pull/103 for discussion, which also mentions http://www.rubydoc.info/gems/twitter which acts in a similar way.

**Comment by Jaco-Pretorius** [comment]
@josler This still doesn't exclude what I'm proposing, someone else even suggested it in the discussion thread.  You could simply configure it in a global configuration block (optionally) and then you can override it when you instantiate the `Intercom::Client`.

So `intercom = Intercom::Client.new` would use the global config, `intercom = Intercom::Client.new(app_id: your_app_id, api_key: your_api_key)` would override the global config, or set it when it wasn't specified in a global block.

It just seems like the majority of users don't use Intercom in a multi-tenant environment, so this would allow the regular use case to be very simple while still allowing for the multi-tenant use case.

**Comment by bobjflong** [comment]
hi @Jaco-Pretorius -

You can do global configuration, you just need to use a global client. For example, in an initialiser or similar: `$intercom = Intercom::Client.new(app_id: 'my_app_id', api_key: 'my_api_key')`. This global client will encapsulate the app_id and app_api_key. You won't have to specify it every time.

If using clients is a deal-breaker, you could maybe check out a [slightly older release](https://github.com/intercom/intercom-ruby/tree/v2.5.4).

**Comment by rubendinho** [comment]
Now that the client configuration options have been simplified, are there any plans to revisit this issue?
