### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by gevans** [intercom/intercom-ruby#178]
The current test suite makes me feel uneasy by relying heavily on stubbing out methods and returning prewritten responses kept in [`spec_helper.rb`](https://github.com/intercom/intercom-ruby/blob/86a42dcd7cc05da893f8343f651e5cbf86b38a6c/spec/spec_helper.rb#L5-L449).

Using a library like [vcr](https://github.com/vcr/vcr#readme) to record and replay HTTP interactions would make it easy to test against a real API.

If there's interest in this, I'd be more than happy to get it started.

**Comment by josler** [comment]
That would be great, we'd definitely love to have this.

**Comment by gevans** [comment]
Sorry, it doesn't look like I'll be getting to this any time soon. Would someone else like to take over?

**Comment by abhishekbose87** [comment]
Hi @gevans, I was interested in writing the integration specs for this gem using VCR but I realised that authentication would be a problem when we are making the first request. I'd suggest using `webmock` to stub the http requests and have the prewritten responses in json files. What do you think ?

**Comment by gevans** [comment]
VCR has the ability to [filter sensitive data](https://www.relishapp.com/vcr/vcr/docs/configuration/filter-sensitive-data). I'd definitely use this over webmock to get the full benefits of stubbed requests that can also be disabled and run against a live server.

**Comment by abhishekbose87** [comment]
@gevans I have a question here. I haven't used VCR before, just read docs and played around with gem's code .. so might be a really stupid question. 

For every HTTP request here, I need to send in the `app_id` and `api_key`. So if I go ahead and create a test account in Intercom, and we get VCR working and the tests pass. But after a period of time, if another developer needs to run them against a live server, he would need the same account details. Won't this become a maintenance problem ? Or how do we streamline this ?

**Comment by gevans** [comment]
Other developers should be able to use their own credentials without issue. You just have to make sure you're handling your dependencies in the setup and teardown of your tests. It's the same as running tests against a database... just a little more complicated. :sweat_smile: 

For example, if we wanted to test retrieving a list of users, you would create the users as part of the test rather than referencing existing records. That way, your tests can run without depending on resources might not exist or you don't have permission to access.

**Comment by abhishekbose87** [comment]
Thanks @gevans for clearing out my confusion. I will take a jab at this.

If possible, can you suggest an open source repo which is using VCR. Would be a helpful reference.

**Comment by choran** [comment]
Hi All, 
VCR does seem interesting and it is something that I think would be useful. I was not aware of it previously. At the moment however I do not think we have any short term plans to add this feature. But we would like to facilitate the community conversation where this discussion takes place. GitHub issues might not be the best location for this so we are trialing a developer forum called [Gitter](https://gitter.im/intercom/intercom-ruby) which could be more useful in this regard. We are just starting this up so take a look and let us know what you think and what works best. Would love to know how you think we could best help facilitate these type of discussions.
If you feel GitHub issues are the best lace for this please feel free to re-open this.
