### ISSUE TITLE
Notification payload

### ISSUE THREAD

**Issue by jetienne** [intercom/intercom-ruby#180]
Hi,

It seems v3.x does not include the Notification model and its payload deserialize feature? Any plan?

**Comment by josler** [comment]
Hey, 

Yes, it does not currently. I'll look at adding that soon, would something like:

```ruby
client.notifications.load(some_hash_payload)
# returns Intercom::Notification model as before.
```

suit?

**Comment by jetienne** [comment]
Would be perfect! Any ETA? :)

**Comment by josler** [comment]
No ETA right now sorry!

One way you could do this right now would be to do something like:

```ruby
convo = Intercom::Conversation.new(some_webhook_hash["data"]["item"])
```

as per:

https://doc.intercom.io/api/#subscription-model

The inner data.item object has a type field too.

Does that help?

**Comment by choran** [comment]
Hi @jetienne 
Were you able to use the workaround suggested above? We have reviewed this and will not be making any changes in relation to the notification model. The workaround above seems to provide the requested functionality so there does not seem to be any significant requirement to add the notification model. I will close this issue but if you had any issues implementing the above workaround please let us know.
