### ISSUE TITLE
Assigning Conversation

### ISSUE THREAD

**Issue by rossgeesman** [intercom/intercom-ruby#181]
I'm trying to figure out how to assign conversations to an admin. Let's say I have an Intercom::Conversation object called 'convo' and a Intercom::Admin object called admin:

```
convo.assignee = admin
INTERCOM_API.conversations.save(convo)
```
This is giving me NameError: undefined local variable or method `id'. Am I doing this wrong? Is this not supported by the API or wrapper?

**Comment by bscanlan** [comment]
Hey Ross!

We're literally working on conversation assignment APIs this week :smile_cat: 

We expect to have Ruby SDK support next week. If something terrible happens and we don't get to it as expected, I'll update this issue.

**Comment by rossgeesman** [comment]
Awesome thanks!

**Comment by bobjflong** [comment]
Hi @rossgeesman - the attached PR should demonstrate how to assign conversations via the API. We are planning on improving the interface for assignments in an upcoming release.

**Comment by rossgeesman** [comment]
Thanks so much for keeping me in the loop! I'll let you know if we have any
problems.
