### ISSUE TITLE
Correcting a user's companies programmatically

### ISSUE THREAD

**Issue by mnacos** [intercom/intercom-ruby#188]
It seems like Intercom never forgets companies already associated with a user. We're trying to correct a user's companies but we're unable to do this via the API.

e.g. 

    intercom_user = Intercom::User.find(user_id: 'some-id')
    intercom_user.companies = intercom_user.companies.select {|c| c.name == 'Company1'}
    intercom_user.save

does not actually modify the list of companies the user has been associated with.

Is there a way? The code above uses version 2.5.4 of the gem.

**Comment by josler** [comment]
Hey,

There is a way, if you set the hash key `:remove => true` for those companies you want to remove from a user that will do it. In your example:

```ruby
intercom_user = Intercom::User.find(user_id: 'some-id')
intercom_user.companies =  [ { company_id: 'Company1', remove: true } ]
intercom_user.save
```

Cheers!

**Comment by mnacos** [comment]
thanks
