### ISSUE TITLE
Attempting to specify message reply type of 'thumbs' or 'emoticon'

### ISSUE THREAD

**Issue by dkc90** [intercom/intercom-ruby#190]
We are attempting to utilize the feature allowing for an admin user sending a message to specify a response type of 'Thumbs' or 'Emoticon' like you can do from within the Intercom message sending GUI:

![screen shot 2015-08-18 at 2 02 46 pm](https://cloud.githubusercontent.com/assets/8540334/9338271/df11d718-45b1-11e5-80cb-08a889d90b23.png)

The gem and the API documentation don't appear to have anything documenting how to accomplish this, so we were wondering if it is actually possible to accomplish this via the API, and if so, how it can be achieved.

**Comment by josler** [comment]
Hi @dkc90,

It's not currently possible to use Lightweight Replies (Thumbs, Emoticons) via the API. It's something we've considered, but are unlikely to do in the immediate future. Ideally there would be some iteration on this to make it more applicable for a wider range of things first.

Thanks!
