### ISSUE TITLE
Intercom::UnexpectedError

### ISSUE THREAD

**Issue by zitooon** [intercom/intercom-ruby#191]
Hi

I'm using 'Intercom.users.save' method to update some users and when I manually set a user_id for a user that havent one before I get an exception: "Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: User already exists. and http_code: '400'. Please contact Intercom with these details."
````ruby
intercom_user.custom_attributes = intercom_user.custom_attributes.merge(custom_attributes)
intercom_user.user_id = user_id
intercom.users.save(intercom_user)
````
Can you please give me some explanations on was is going on here ?

Thanks a lot !

**Comment by josler** [comment]
Hi @zitooon - the error message is telling you that there exists another user in Intercom with that user_id already.

**Comment by zitooon** [comment]
Hi @josler,

thanks for the answer (even 16 days after), but I figure it out by myself and I think that in your api documentation the fact that the user_id is uniq isn't clear enough in my opinion.

Anyway thanks, I'm closing the issue
