### ISSUE TITLE
Check if user exists on intercom side

### ISSUE THREAD

**Issue by gearoidoceallaigh** [intercom/intercom-ruby#192]
We've been having sporadic issues with users not being created on the intercom side. This leads to exceptions in subsequent calls. Would be nice to have a simple check we can perform against. At the moment I'm doing something like the following:

```
begin
  Intercom::User.find(user_id: <<USER-d>>)
  # do whatever
rescue Intercom::ResourceNotFound
  # user not found - try to create on intercom side again
end
```

**Comment by josler** [comment]
Hi @gearoidoceallaigh - I don't think there's anything to add to the gem here? Is there anything you need that's not present?

**Comment by gearoidoceallaigh** [comment]
Hi @josler 

Well, ideally something like the following which would return a boolean:

```
Intercom::User.exists?(user_id: <<USER-ID>>)
```

Would be nice to query against email (or other unique fields).

**Comment by josler** [comment]
The way we'd implement that would just be to do the Begin/Rescue as you mentioned above, but wrapped in a function. Not sure that that sort of specific functionality belongs in the client library as each use case would be different. An example snippet you could use in your own application:

```ruby
def with_existing_intercom_user(user_id)
  Intercom::User.find(user_id: user_id)
  yield
rescue Intercom::ResourceNotFound
  Intercom::User.create(user_id: user_id)
  yield
end
```

**Comment by gearoidoceallaigh** [comment]
Hmmmm, true enough :)

Closing this. Thanks!

**Comment by travisdmathis** [comment]
responding to this, as it would be a lot nicer and dryer code to implement in the library find_or_create

**Comment by josler** [comment]
@travisdmathis - our user api creates users if they don't exist on a POST /users call.

https://doc.intercom.io/api/#create-or-update-user

**Comment by travisdmathis** [comment]
I was looking at contacts, not users.  Contacts it just keeps creating more contacts w/ the same email.

**Comment by josler** [comment]
For Contacts that's intended - email is not a record of uniqueness there (a non logged in people could provide any email they like).

For Contacts I'd keep a record of the unique user_id we assign, if you're intending to track between sessions, as that's the record of uniqueness. Or use Users if you're tracking logged in people with verified/unique emails.

**Comment by travisdmathis** [comment]
gotcha thanks for the clarity!

**Comment by aitfriha** [comment]
$existe = 1; 
try {
                $test = $intercom->getUser(array(
                    "user_id" => "12"
                ));
            } catch (\Intercom\Exception\IntercomException $e) {
                $existe = 0;
            }
if ($existe == 1) {
            $intercom->deleteUser(array("user_id" => "12"));
        }
