### ISSUE TITLE
How to send events in the background?

### ISSUE THREAD

**Issue by alexhanh** [intercom/intercom-ruby#193]
I'd image the call to the Intercom API (similar to a call to any other 3rd party API) should be processed in the background because of the HTTP overhead to not keep the user waiting.

Unfortunately, I haven't found any recommendations on how to do it. In our specific case, we are using DelayedJob as the background queue. 

Any help is more than welcome. Thanks!

**Comment by josler** [comment]
Hey @alexhanh,

If you'd like to process requests in the background using DelayedJob I think you would just need to create a IntercomJob class or the like with a `process` method on it as described in the documentation. This client library doesn't provide this out of the box, but should work just fine.

Thanks!
