### ISSUE TITLE
`Intercom::AttributeNotSetError` when saving user

### ISSUE THREAD

**Issue by pletcher** [intercom/intercom-ruby#196]
Hi,

I have a bit of code that follows the examples in the README pretty closely:

```ruby
intercom_user = intercom.users.find(user_id: user.id)
intercom_user.custom_attributes["referral_token"] = user.referral_token
intercom_user.custom_attributes["organization"] = account.domain
intercom_user.signed_up_at = user.created_at
intercom.users.save(intercom_user)
```

But when that last line runs, Intercom throws an error (it's always the same, no matter what user is being updated):

```ruby
#<Intercom::AttributeNotSetError: 'to_ary' called on Intercom::User but it has not been set an attribute or does not exist as a method>
```

Any idea what's wrong?

**Comment by josler** [comment]
Hey @pletcher 

What values are you setting as custom data there?

**Comment by pletcher** [comment]
Hey @josler,

The values are url-safe strings -- `user.referral_token` is the result of `SecureRandom.urlsafe_base64(nil, false)` and `account.domain` is just a bare subdomain (not really well named, I guess) with no qualifiers, e.g. `github`.

**Comment by josler** [comment]
Hm.

Is `user.created_at` a timestamp? Perhaps try with `.to_i` on it if not (the API takes timestamps).

**Comment by pletcher** [comment]
`user.created_at` is a timestamp, but I'll try it with `.to_i` just in case.

**Comment by pletcher** [comment]
Hey @josler, tried your suggestion -- unfortunately, I get the exact same error as before.

Here's a rundown (with some bits redacted) of what the logs look like:

```
ADDING REFERRAL_TOKEN fOaqh-rF5VUZDi47HjkgUA FOR USER 123
ADDING SLACK_ORGANIZATION company_xyz FOR USER 123
ADDING SIGNED_UP_AT 2015-08-14 23:21:55 UTC FOR USER 123

UPDATING:

#<Intercom::User:0x007f2e53512c90 @changed_fields=#<Set: {"signed_up_at"}>, @custom_attributes={"organization"=>"company_xyz", "referral_token"=>"fOaqh-rF5VUZDi47HjkgUA"}, @id="{intercom_id}", @user_id="{user_id}", @anonymous=false, @email="email@email.com", @name="Somebody", @pseudonym=nil, @avatar=#<Intercom::Avatar:0x007f2e53511cc8 @changed_fields=#<Set: {}>, @image_url=nil>, @app_id="wdc55lmn", @companies=[#<Intercom::Company:0x007f2e53511138 @changed_fields=#<Set: {}>, @custom_attributes={}, @company_id="{company_id}", @id="{intercom_company_id}", @name="Company XYZ">], @location_data={}, @last_request_at=nil, @last_seen_ip=nil, @created_at=1442264426, @remote_created_at=1439594515, @signed_up_at=1439594515, @updated_at=1442338405, @session_count=0, @social_profiles=[], @unsubscribed_from_emails=false, @user_agent_data=nil, @tags=[], @segments=[]>

-------------------

SAVING #<Intercom::User:0x007f2e53512c90>

SOMETHING WENT WRONG FOR USER 123

#<Intercom::AttributeNotSetError: 'to_ary' called on Intercom::User but it has not been set an attribute or does not exist as a method>
```

**Comment by josler** [comment]
(we now support sorting by updated_at when getting all users)

**Comment by josler** [comment]
I had a deeper look into this, and it looks like there was an error when calling `puts` with an api_resource, due to some of the method_missing swizzling :disappointed:, as puts calls `to_ary`,

I've fixed this now, if you update your gem version to `3.2.0`.

**Comment by pletcher** [comment]
Oh, interesting -- thanks for tracking that down! I've updated and the issue seems to be resolved :)
