### ISSUE TITLE
The error of type '' is not recognized. It occurred with the message: Unauthorized and http_code: '401'. Please contact Intercom with these details.

### ISSUE THREAD

**Issue by carvil** [intercom/intercom-ruby#198]
Hi,

When connecting to the client with invalid credentials, we were expecting an error of type `Intercom::AuthenticationError`, but instead we are getting this:

```
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Unauthorized and http_code: '401'. Please contact Intercom with these details.
```

We are using `3.2.0` and in a console running the following:

```
intercom_client = Intercom::Client.new(app_id: '', api_key: '')
intercom_client.events.create({ event_name: 'my-event', email: 'me@gmail.com' })
```

Is it possible to raise a `Intercom::AuthenticationError` instead?

Thanks

**Comment by josler** [comment]
Thanks @carvil - I've added this to the other issue as it's the same thing. Cheers.
