### ISSUE TITLE
Bulk APi

### ISSUE THREAD

**Issue by karellm** [intercom/intercom-ruby#202]
Hi,

Is there any chance to see the bulk api in the gem? We need a way to update data about our users and companies periodically and we will likely hit the limit without the bulk api.

If I work on it, will you merge the PR (I noticed some PRs don't get answered or merged)?

**Comment by RuairiK** [comment]
Hi Karel,

We're working on adding this at the moment, this feature will be available in the gem in the next few days. So, no need for you to work on it :).

**Comment by karellm** [comment]
Looking forward to it

**Comment by RuairiK** [comment]
Bulk API operations are now supported in the gem. Let us know if you have any feedback.

**Comment by karellm** [comment]
@RuairiK Thanks but it does not look from the docs that you support bulk user update. Am I missing something?

**Comment by fskinner** [comment]
I also need this bulk user update @karellm have you find a way to do that?

**Comment by RuairiK** [comment]
@fskinner The `create_items` in `user` parameter can be used both for creating and updating users. It works in the same way. Just pass in the users you wish to update. https://github.com/intercom/intercom-ruby#users

**Comment by fskinner** [comment]
@RuairiK oh thanks! It will update if I pass a user that matchs an existing intercom user, is that right?

**Comment by RuairiK** [comment]
@fskinner Yes, exactly :).

**Comment by fskinner** [comment]
Thanks for the great help! :)

**Comment by fskinner** [comment]
Also, I think it would be an useful information on the README !

**Comment by RuairiK** [comment]
No problem. You're probably right, I'll make it clearer now :)
