### ISSUE TITLE
Bulk company API

### ISSUE THREAD

**Issue by karellm** [intercom/intercom-ruby#204]
Hi,

Thanks for the Bulk API, it works great for users. Though my attempts to use it for companies were unsuccessful. From the docs, it does not look like it is supported. Do you plan on adding this in the future? Am I missing something?

Thanks

**Comment by RuairiK** [comment]
Hi Karel,

Really glad you are finding the bulk API useful. We currently only support bulk operations on users and events. We are looking at adding support for companies in the future, but not immediately.
