### ISSUE TITLE
Tag.find doesn't work as expected

### ISSUE THREAD

**Issue by thesmart** [intercom/intercom-ruby#206]
```
tags = intercom.tags.find({ name: "my_tag_name" })
```

I would expect this to return a single tag that matches name.  However, it returns an object of type `Intercom::Tag` that looks like:

```
puts tags.to_json
{
  "tags": [
    {
      "type": "tag",
      "id": "191866",
      "name": "my_tag_name"
    },
    {
      "type": "tag",
      "id": "191850",
      "name": "bingbat"
    },
    {
      "type": "tag",
      "id": "149207",
      "name": "foobar"
    }
  ]
}
```

**Comment by thesmart** [comment]
```
tags = intercom.tags.find({ name: "my_tag_name" })
```

I would expect this to return a single tag that matches name.  However, it returns an object that looks like:

```
{
  "tags": [
    {
      "type": "tag",
      "id": "191866",
      "name": "my_tag_name"
    },
    {
      "type": "tag",
      "id": "191850",
      "name": "bingbat"
    },
    {
      "type": "tag",
      "id": "149207",
      "name": "foobar"
    }
  ]
}
```

**Comment by bobjflong** [comment]
Hey @thesmart I don't see `tags.find` documented here, and there is no API level support for finding by name https://developers.intercom.io/docs/list-tags-for-an-app (only listing all). Looks like we need to remove this: https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/service/tag.rb#L4
