### ISSUE TITLE
Bulk API

### ISSUE THREAD

**Issue by romanmasalov** [intercom/intercom-ruby#207]
Hi,

I'm trying to use the Bulk API, and received the following error
```
{
    "errors": [
        {
            "code": "media_type_not_acceptable",
            "message": "The Accept header should send a media type of application/json"
        }
    ],
    "type": "error.list"
}
```

Rails 3.2.22
ruby 2.1.0p0

Thanks

**Comment by RuairiK** [comment]
Hi,

I don't think you should ever get that error through the ruby gem. What action are you trying to perform that generates this error? What function are you calling?

**Comment by romanmasalov** [comment]
Hi.

irb(main):017:0* resp = ic.events.submit_bulk_job(create_items: [
irb(main):018:2*   {
irb(main):019:3*     event_name: "LS_Completed",
irb(main):020:3*     created_at: Time.now.to_i,
irb(main):021:3*     user_id: "8710"
irb(main):022:3>   }
irb(main):023:2> ])
=> #<Intercom::Job:0xbebce620 @changed_fields=#<Set: {}>,
@app_id="af2xbg6c", @id="job_f7edac04_8c82_11e5_865a_2da3903c329e",
@created_at=1447692983, @completed_at=nil, @closing_at=1447693883,
@updated_at=1447692983, @name="api_bulk_job", @state="running",
@links={"error"=>"
https://api.intercom.io/jobs/job_f7edac04_8c82_11e5_865a_2da3903c329e/error",
"self"=>"
https://api.intercom.io/jobs/job_f7edac04_8c82_11e5_865a_2da3903c329e"}>

**Comment by RuairiK** [comment]
I think you may be trying to access the error feed without authenticating. Requests to the error feed need to be authenticated with your API key.

You can access the error feed from the ruby gem by calling the `errors` method like so:
```ruby
# fetch a job's error feed
ic.jobs.errors(id: 'job_f7edac04_8c82_11e5_865a_2da3903c329e')
```
