### ISSUE TITLE
Android 'getUUID' exception

### ISSUE THREAD

**Issue by sharq1** [intercom/intercom-ruby#210]
Some of our clients using Android (4.1.2, 4.2.2, 4.4.2) devices get following exception:
```
Uncaught TypeError: Cannot call method 'getUUID' of undefined
```
Because of that chat is not working.
Any ideas how to solve this?
At the moment I'm unable to get the stack trace, but it would be possible in a two days time if necessary.

**Comment by RuairiK** [comment]
Hi,

Could you provide a little more info on what you're trying to do so we can help you figure out what's going on? This ruby gem is generally used for accessing the rest API, so it shouldn't affect chat. This looks like a javascript error, are you using intercom-rails?

**Comment by sharq1** [comment]
Yes, that's a javascript error - sorry, it's in wrong repository.
