### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by karellm** [intercom/intercom-ruby#211]
Hi,

It is pretty hard to predict the rate limit of the API. First we didn't care, hit the limit. Switch to the bulk API, hit the limit. Spread requests to have no more than 500 requests/min, hit the limit. Implemented `rate_limit_details` but it returns an empty hash `{}`.

Can you please clarify the rate limit rules to use the API? Thanks!

**Comment by bscanlan** [comment]
Hi,

Sorry for your frustration here. Could you provide your app ID so we can investigate why you're hitting rate limits? We can increase the limits quickly while we're troubleshooting here.

The empty hash sounds like a bug - could you supply version details and exactly how to reproduce?

Thanks!

**Comment by karellm** [comment]
@bscanlan Thanks for the quick answer, I emailed you the App ID. Maybe we can continue about the application specific issue privately.

Regarding `rate_limit_details`, here is the code:

```ruby
task rate_limit_details: :environment do
  intercom = Intercom::Client.new(app_id: ENV['INTERCOM_APP_ID'], api_key: ENV['INTERCOM_API_KEY'])
  puts intercom.rate_limit_details
end
```

It is a rake task in a Rails 4.2 app. We use `master` since it does not look like you made a release with the batch API yet. The ENV are the right ones since we can use the API. Let me know if I can provide you with any more information.

**Comment by karellm** [comment]
@bscanlan Did you receive my email?

**Comment by bscanlan** [comment]
Yes - I'll get back to you ASAP
