### ISSUE TITLE
Intercom tries create new user

### ISSUE THREAD

**Issue by VladimirTS** [intercom/intercom-ruby#212]
@darragh @josler When I try send message from admin to user I got next error Intercom::MultipleMatchingUsersError: Multiple existing users match this email address admin@example.com - must be more specific using user_id
But when I wrote intercom.users.find(:email => "admin@example.com")  i didn't get user with email "admin@example.com"

**Comment by bobjflong** [comment]
Hi @VladimirTS the `Intercom::MultipleMatchingUsersError` means that you have duplicate users by email. The user_id field is unique and can be used to discern between them. If you intentionally duplicate by email you should switch to identifying by user_id. If this was accidental you could try your duplicate users.

**Comment by rpavez** [comment]
Hi @bobjflong, I'm running into the same problem and would like to remove users which were accidentally duplicated, the problem is that there doesn't seems to be a way to list all users with a given email, even worse if I try removing the duplicated user manually using the admin website the problem persist.

**Comment by choran** [comment]
Hi @rpavez, one thing you could try here is using the UI to filter you users by email. This should provide you with a list of users with the same email. Then you can export this via a CSV and use the API to delete these users. Do you think that would work for your scenario?  I wasn't sure what you meant when you said the problem persists when you try and delete via the admin website? i.e. they are not deleted?
