### ISSUE TITLE
nil values should be converted to an empty string

### ISSUE THREAD

**Issue by milesmatthias** [intercom/intercom-ruby#220]
If you pass a `nil` value as a custom attribute, you raise an error that says the value should be "Numeric, String, or Boolean".

But if you pass an empty string (`""`) then Intercom still says "Unknown" for that field. So if you pass a `nil` value in the ruby client, you should just convert it to an empty string.

**Comment by RuairiK** [comment]
Can't reproduce, passing `nil` sets the custom attribute to `unknown` as expected.
