### ISSUE TITLE
Unable to delete custom_attributes fields

### ISSUE THREAD

**Issue by thesmart** [intercom/intercom-ruby#223]
I couldn't figure out how to permanently delete a custom_attribute set in a User model.

Doesn't work:
```
i_user.custom_attribute['foobar'] = nil
intercom.users.save(i_user)
i_user.custom_attribute.delete('foobar')
intercom.users.save(i_user)
```

There ought to be a way to delete fields.

**Comment by RuairiK** [comment]
We don't support deleting custom attributes anywhere in Intercom at the moment, I'm afraid. Sending `nil` will simply set the attribute to unknown. You can archive custom attribute from the Intercom web app.

**Comment by naveen-goalous** [comment]
hi, let me introduce you how to change the type of the custom attribute. Take a look...
<img width="640" alt="people_attributes___goalous___intercom" src="https://cloud.githubusercontent.com/assets/17561832/15998004/618992ee-3175-11e6-842a-c26c51e5be74.png">

**Comment by johnculviner** [comment]
@RuairiK is this still the case. I would love to be able to clean up some old fields. Archive is definitely a good idea but without delete things become messy for a long running application relying on Intercom

**Comment by Skaelv** [comment]
Hey @johnculviner I'm afraid nothing has changed since ruairi's last message concerning custom attributes deletion.

**Comment by johnculviner** [comment]
Ahh bummer, thank you for the heads up. Just sneak a ```DELETE``` REST call in there sometime and let me know ;)

**Comment by zachgarcia1** [comment]
I also think the ability to delete attributes should be implemented. I misspelled an attribute and sent it through and now its there forever?

**Comment by Hani-RT** [comment]
Another vote for being able to delete custom attributes.  Things are bound to get messy over time if only "archive" is available.

**Comment by pootzko** [comment]
You don't have to hard delete them. Just soft delete and don't display them anywhere to the user. Or make the archived ones hidden by default and add a button to display them.. Just throwing ideas around.

**Comment by dockermaster** [comment]
The issue is, we used ClearBit and they injected hundreds of fields which are useless to us.
Manually it takes forever to archive a custom_attributes plus there is no multi-select option for that either.
And not allowing it on the API is not dev friendly as well.

Please fix

**Comment by diddeb** [comment]
I am chiming in here. Not supporting deletion of custom attributes is... Silly.

**Comment by imcorey** [comment]
This really needs to happen here and in several other places in intercom.

**Comment by antwonlee** [comment]
Same.  Clearbit injected too many useless attributes.

**Comment by cayleyh** [comment]
Still something we struggle with a lot -- we have a lot of old data & we are constantly evolving what we send & how we send to providers. Without a better way to manage these changes, Intercom just becomes and unworkable mess. Please please please have a way to archive or soft delete via an API call!!

**Comment by borisgefter** [comment]
Ditto, this is a weird lack of a function.
Guys you gotta get on top of this!

**Comment by jstetic** [comment]
I agree, deleting is needed.  Or at least at a minimum when an attribute is archived users stop seeing it in the UI.

**Comment by kvognar** [comment]
If there's a hard limit on the number of custom attributes you can have, you _really_ need a way to delete old attributes. Otherwise, there will inevitably be tons of customers running up against a concrete wall with no way to fix it.

**Comment by Onebri** [comment]
hey @kvognar,
the limit is set at 250 custom data attributes per workspace.
we're having the same issue & we don't know if archiving helps to get back data attributes 'credits'
