### ISSUE TITLE
Find users and companies with custom fields?

### ISSUE THREAD

**Issue by onurozgurozkan** [intercom/intercom-ruby#230]
We plan to create [event](https://github.com/intercom/intercom-ruby#events) after a phone call. Phone numbers are custom fields in intercom. We need to find users and companies by custom fields.

```ruby
users = intercom.users.find(:gsm => "+90532620xxxx") # gsm is custom field
companies = intercom.companies.find(:gsm => "+90532620xxxx") # gsm is custom field
```

Any idea?

**Comment by RuairiK** [comment]
We don't support listing users by custom attributes directly from the API but I think something like this should do what you want:
```ruby
users = intercom.users.all.select{|user| user.custom_attributes['gsm'] == '+90532620xxxx'}
```

**Comment by Jeromearsene** [comment]
Too bad ! 
Your idea @RuairiK is functional but is very slow.
