### ISSUE TITLE
No way to access all the posts under a conversation

### ISSUE THREAD

**Issue by kazimzaidi** [intercom/intercom-ruby#239]
This is a feature request. If I load a conversation which has got responses from the user and our team, there's no way to load those responses.

If that's not possible, is there a way to know all the participants in a given conversation?

I can see that its possible to post a new reply, but not possible to read existing replies.

**Comment by RuairiK** [comment]
Hi,

This functionality already exists. 

```ruby
conversation = intercom.conversations.find(:id => '1')
conversation.conversation_parts
```
https://github.com/intercom/intercom-ruby#conversations
