### ISSUE TITLE
media_type_not_acceptable when sending bulk job request

### ISSUE THREAD

**Issue by ikhakoo** [intercom/intercom-ruby#240]
I'm getting the following error when submitting a bulk job request

{
    "errors": [
        {
            "code": "media_type_not_acceptable",
            "message": "The Accept header should send a media type of application/json"
        }
    ],
    "type": "error.list"
}

## Version info
  - intercom-ruby version: gem 'intercom', "~> 3.4.0"
  - Ruby version: ruby '2.3.0'

Have tried debugging and also have attempted to contact intercom to no avail. Any help would be appreciated. I see others have had this issue but the resolution was not posted in the github issue.

**Comment by ikhakoo** [comment]
I figured out the issue after reading through the API Docs and there needs to be a second hash which contains "custom_attributes" (i.e. anything not out of the box at intercom).  Adding this resolved my issue.

**Comment by LuisCDias** [comment]
@ikhakoo Can you give an example of a request? I'm including "custom_attributes" inside each user in the bulk request but I'm still getting the same error
