### ISSUE TITLE
Cannot Bulk Submit User Jobs

### ISSUE THREAD

**Issue by twistedup90** [intercom/intercom-ruby#241]
## Version info
  - intercom-ruby version: 3.4.0
  - Ruby version: 2.3.0

## Expected behavior
Job successfully submitted

## Actual behavior
https://api.intercom.io/jobs/job_c61b89e8_083e_11e6_874d_1132f062216e/error

{
    "errors": [
        {
            "code": "media_type_not_acceptable",
            "message": "The Accept header should send a media type of application/json"
        }
    ],
    "type": "error.list"
}

## Steps to reproduce
 1. job = intercom.users.submit_bulk_job(create_items: { ... })

## Logs

**Comment by RuairiK** [comment]
Hi, 

You need to authenticate before accessing the error feed endpoints. There is a method in the ruby sdk to do this for you. https://github.com/intercom/intercom-ruby#bulk-jobs

I can see from our internal logs that your job completed successfully.

**Comment by ngouy** [comment]
Same problem here ... I'm trying to push data to my app with my personal ids (api_key and app_id), but i get https://api.intercom.io/jobs/job_1f917e70_2756_11e6_af5b_6941db9f73d5/error
with the code in the exemple 
```
bulk = client.users.submit_bulk_job(create_items: [{user_id: 25, email: "alice@example.com"}, {user_id: 25, email: "bob@example.com"}])
```

But I can add a new user by sending client.users.create(:email => "test@test.test")

Funny thing is that my job worked because users appeared in my app board.

Is it a bug ? Or can't we know if the job really worked or not ?

regards

**Comment by rydstein** [comment]
https://intercomrades.intercom.io/a/apps/tx2p130c/inbox/ryan.steinberg@intercom.io/conversations/4920504828

**Comment by ngouy** [comment]
?

**Comment by rydstein** [comment]
My mistake, posted that link in the wrong github issue (tracking purposes). Sorry for the confusion!

**Comment by choran** [comment]
@ngouy 
No this is not a bug, you cannot access the http links directly, that is where the error is coming from. Instead you need to use one of the bulk job methods to check the state or the errors:
# fetch a job state
intercom.jobs.find(id: 'job_abcd1234')
# fetch a job's error feed
intercom.jobs.errors(id: 'job_abcd1234')

If you use these with the returned job id you should then be able to see the state or the errors if there are any. The object will also tell you when the job started and when it completed. If you have any other bulk job question please reach out to our CS team at team@intercom.io. You will probably receive a quicker response to these type of issues there. 

thanks
Cathal
