### ISSUE TITLE
Supporting created_since

### ISSUE THREAD

**Issue by lcpriest** [intercom/intercom-ruby#243]
## Version info
  - intercom-ruby version: 3.4.0
  - Ruby version: 2.2.4

## Expected behavior
client.users.find_all({created_since: 60.seconds.ago.utc.to_i}).first(5)
=> []

## Actual behavior
client.users.find_all({created_since: 60.seconds.ago.utc.to_i}).first(5)
=> Array of users created more than 60 seconds ago

Do you know how to filter by created_since? Is it in the gem?
Re: https://developers.intercom.io/reference#list-users

**Comment by olliebennett** [comment]
Appreciate this is a bit clunky as a workaround, but you can set up any filters you may need as a segment (via the Intercom dashboard) and then retrieve only the users from that segment:

```ruby
intercom_client.users.find_all(segment: 'my-segment-id').each do |intercom_user|
    puts %Q(#{intercom_user.user_id}, #{intercom_user.email})
end
```

The segment ID is taken from the URL while viewing the segment on the dashboard.

**Comment by lcpriest** [comment]
100% my mistake - the API documentation doesn't even talk about unix timestamps. It filters by number of days.

`{ created_since: 1 }` means users created in the last day.
