### ISSUE TITLE
Event return Invalid metadata

### ISSUE THREAD

**Issue by danieldocki** [intercom/intercom-ruby#244]
Folks,

When a created an event not working properly, return *Invalid metadata*

## Version info
  - intercom-ruby version: 3.4.0
  - Ruby version: 2.2.3

## Expected behavior

```
intercom.events.create(
  :event_name => "sent-deal",
  :created_at => Time.now.to_i,
  :user_id => user.id,
  :metadata => {
    :id => 402,
    :description => "oii",
    :amount => 100.0,
    :contact => {
      :id=>102,
      :name=>"Daniel Docki",
      :email=>"xxxxx",
      :phone=>"xxxxx"
    }
  }
)
```

## Actual behavior
![screen shot 2016-04-28 at 18 56 33](https://cloud.githubusercontent.com/assets/10542/14902691/fee6bce6-0d72-11e6-9b47-981a7f466522.png)

## Steps to reproduce
 1.  Create a event

**Comment by Skaelv** [comment]
Hey
Events metadata do not currently support trees. You should probably flatten your contact.
If you want you can contact our support team and propose the feature request explaining why you would need to store metadata as a tree.
