### ISSUE TITLE
"Intercom::Job" object doesn't set its @state and @completed_at variables correctly

### ISSUE THREAD

**Issue by epitron** [intercom/intercom-ruby#245]
## Version info
  - intercom-ruby version: 3.4.0
  - Ruby version: 2.3.1

## Expected behavior

`intercom.jobs.find(id: <the job-id>)` should display the current state of the job

## Actual behavior

```
> intercom.jobs.find id: "job_86e43e1c_129a_11e6_9246_51c973072fb5"
=> #<Intercom::Job:0x0000000b3bbef0
 @app_id="kawxi0ca",
 @changed_fields=#<Set: {}>,
 @closing_at=1462437457,
 @completed_at=nil,
 @created_at=1462436557,
 @id="job_86e43e1c_129a_11e6_9246_51c973072fb5",
 @links=
  {"error"=>"https://api.intercom.io/jobs/job_86e43e1c_129a_11e6_9246_51c973072fb5/error",
   "self"=>"https://api.intercom.io/jobs/job_86e43e1c_129a_11e6_9246_51c973072fb5"},
 @name="api_bulk_job",
 @state="running",
 @tasks=
  [{"id"=>"task_86eab6ca_129a_11e6_b85f_2726d926b34f",
    "item_count"=>4,
    "created_at"=>1462436557,
    "started_at"=>1462436557,
    "completed_at"=>1462436558,
    "state"=>"completed"}],
 @updated_at=1462436557>
```

The job is completed -- as you can see by looking at `@tasks` -- but `@state` still says "running". Also, `@completed_at` is still nil.

## Steps to reproduce
 1. job = intercom.users.submit_bulk_job(...)
 2. `<wait a few seconds>`
 3. intercom.jobs.find(id: job.id)

**Comment by ngouy** [comment]
And entre parenthèses there is an error link even if (if I understand sell) the job worked.
The self link point an error page too.

**Comment by epitron** [comment]
So I'm supposed to look at the individual tasks in the job to tell if it's finished?

**Comment by choran** [comment]
Yes, you will need to check the state of the individual tasks to check how your particular task is doing. I looked through this and we create a task for each job. You can add multiple tasks to one job. We go through each task in a job to check their state whenever you check the state of the job itself. But we do not update the state of the overall job with the same process. 
As a result the state of the overall job will be open for longer than the individual tasks. You can then add more tasks to this job. So whenever you check a job you will need to check the states of the individual tasks. If you are adding tasks to a job then you can check the state of the overall job itself to see if it is still running.
Hope that helps.
Please reopen this is you have any other questions or else you can reach out to our CS team via team@intercom.io
