### ISSUE TITLE
NoMethodError (undefined method `tr' for nil:NilClass)

### ISSUE THREAD

**Issue by samcambridge** [intercom/intercom-ruby#249]
## Version info
  - intercom-ruby version: 3.4.0
  - Ruby version: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

## Expected behavior
We're experiencing this when trying to create an event:

```
   @intercom.events.create(
       :event_name => "created-venue",
       :created_at => Time.now.to_i,
       :email => current_user.email,
       :metadata => {
          "venue_name" => @venue.name
       }
    )
```
## Actual behavior
Error is raised.

## Logs
```
May 12 10:05:59 project bundle[1978]: NoMethodError (undefined method `tr' for nil:NilClass):
May 12 10:05:59 project bundle[1978]: app/controllers/customer/venues_controller.rb:16:in `create'
```

**Comment by sarahjschultz** [comment]
Bumping this -- we're seeing it as well. 
`gem 'intercom', '~> 3.4.0'`
`ruby '2.2.4'`

Stack trace on our end looks like:
```
undefined method `tr' for nil:NilClass

/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/cgi/util.rb:18:in `unescape'
/app/vendor/bundle/ruby/2.2.0/gems/intercom-3.4.0/lib/intercom/request.rb:18:in `set_basic_auth'
/app/vendor/bundle/ruby/2.2.0/gems/intercom-3.4.0/lib/intercom/request.rb:63:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/intercom-3.4.0/lib/intercom/client.rb:107:in `execute_request'
/app/vendor/bundle/ruby/2.2.0/gems/intercom-3.4.0/lib/intercom/client.rb:84:in `get'
/app/vendor/bundle/ruby/2.2.0/gems/intercom-3.4.0/lib/intercom/api_operations/find.rb:10:in `find'
```

Failing when we try to create a new client: 
```
intercom = Intercom::Client.new(app_id: ENV['INTERCOM_APP_ID'], api_key: ENV['INTERCOM_API_KEY'])
```

**Comment by sarahjschultz** [comment]
Accidentally deleted my comment :facepalm: -- bumping this, we're seeing the issue as well.

**Comment by jonseaberg** [comment]
I had this problem in the past and it was because I forgot to set the the environment variable for my api key.  Not saying that is your problem.  Just throwing it out there.

**Comment by samcambridge** [comment]
@jonseaberg thanks for this - you made me double check my servers envionrment variables and I hadn't added my token like I thought I had!

@sarahjschultz this may also fix your issue.
