### ISSUE TITLE
Installing intercom on Ruby 1.9.3  

### ISSUE THREAD

**Issue by shwetasinghgosal** [intercom/intercom-ruby#254]
## Version info
  - intercom-ruby version: 3.5.1
  - Ruby version: 1.9.3

## Actual behavior
Unable to install the intercom on the ruby version 1.9.3. Is there any version of intercom that supports ruby 1.9.3?
The intercom version 3.5.1 is asking for the > 2.1.

**Comment by Skaelv** [comment]
Hey,
We don't support 1.9.3 since v2.5.4.
You can do `gem 'intercom', ,'2.5.4'` **but** the best is probably that you update your ruby version.

**Comment by steverob** [comment]
@Skaelv Is there any  way to use the latest Intercom Authentication method based on `access_tokens`? Thanks!!
