### ISSUE TITLE
Exception when creating event

### ISSUE THREAD

**Issue by satyavh** [intercom/intercom-ruby#260]
I can't create an event. Every time I get an `Intercom::BadRequestError` with error `missing parameter data`

## Version info
  - intercom-ruby version: 3.5.1
  - Ruby version: 2.1.1

## Expected behavior
Create an event

## Actual behavior
I get an Intercom::BadRequestError

## Steps to reproduce
I track like this:

```
      query = {
        event_name: event,
        created_at: Time.now.to_i,
        email: user.email
      }

      INTERCOM.events.create(query)
```

passing data:
```
event: 'file uploaded'
email: 'user@example.com'
```

See logs

## Logs

```
Exception
Intercom::BadRequestError
Error
missing data parameter
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/intercom-3.5.1/lib/intercom/request.rb:140:in `raise_application_errors_on_failure'
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/intercom-3.5.1/lib/intercom/request.rb:94:in `parse_body'
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/intercom-3.5.1/lib/intercom/request.rb:70:in `block in execute'
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/intercom-3.5.1/lib/intercom/request.rb:65:in `execute'
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/intercom-3.5.1/lib/intercom/client.rb:111:in `execute_request'
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/intercom-3.5.1/lib/intercom/client.rb:92:in `post'
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/intercom-3.5.1/lib/intercom/api_operations/save.rb:26:in `save'
/Users/satya/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/intercom-3.5.1/lib/intercom/api_operations/save.rb:18:in `create'
/Users/satya/Development/fileboard-new/app/models/jobs/track_event.rb:71:in `perform'
```

**Comment by satyavh** [comment]
OK I fixed this by explicitly converting `event` and `user.email` to_s

**Comment by Adverbly** [comment]
Just in case someone else gets stuck on this and the above doesn't work: I got the exact same error from not including `created_at` when creating an event. One would think that it would be optional, especially given that the gem can always call `Time.now.to_i`... but nope, its mandatory, but the gem doesn't validate it, and the API responds with a cryptic "missing data parameter".

**Comment by ruanltbg** [comment]
Even though email or user_id is not required by API specification I am receiving this erro when I am not sending it, the thing is, I don't have a user.....
