### ISSUE TITLE
Doc fix

### ISSUE THREAD

**Issue by skryl** [intercom/intercom-ruby#267]
The following example in the docs is incorrect:

```ruby
intercom.messages.create({
  :message_type => 'inapp',
  :body => "What's up :)",
  :from => {
    :type => 'admin',
    :id   => "1234"
  },
  :to => {
    :type => "user",
    :id   => "5678"
  }
})
```

the 'to' hash should look like this:

```ruby
 :to => {
    :type => "user",
    :user_id   => "5678"
  }
```

I'm guessing this applies to other examples as well.

**Comment by choran** [comment]
hey @skryl, you can use either user_id or id for the to field. the api docs explain it [here](https://developers.intercom.io/reference#admin-initiated-conversation). But I can see how this is confusing, it looks like a user_id rather than an id. I will change the id to look more like an id

**Comment by choran** [comment]
ok, updated the README to reflect that it looks like a user_id rather than id
