### ISSUE TITLE
random Intercom::UnexpectedErrors being returned - undocumented

### ISSUE THREAD

**Issue by Tongboy** [intercom/intercom-ruby#268]
Experienced with gem versions 3.5.1 & 3.5.2 running ruby 2.2.4p230

Started seeing these errors in newrelic a few days ago - very random, very rare

Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Server Error and http_code: '500'. Please contact Intercom with these details.

We would have just ignored them if they didn't implicitly ask to tell intercom about them, so here I am :smile: 

Stack trace:
```
…gems/2.2.0/gems/intercom-3.5.2/lib/intercom/
request.rb: 152:in `raise_application_errors_on_failure'
…gems/2.2.0/gems/intercom-3.5.2/lib/intercom/
request.rb:  94:in `parse_body'
…gems/2.2.0/gems/intercom-3.5.2/lib/intercom/
request.rb:  70:in `block in execute'
      /opt/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/
http.rb: 853:in `start'
…gems/2.2.0/gems/intercom-3.5.2/lib/intercom/
request.rb:  65:in `execute'
…/gems/2.2.0/gems/intercom-3.5.2/lib/intercom/
client.rb: 111:in `execute_request'
…/gems/2.2.0/gems/intercom-3.5.2/lib/intercom/
client.rb:  92:in `post'
…ems/intercom-3.5.2/lib/intercom/api_operations/
save.rb:  26:in `save'
…ems/intercom-3.5.2/lib/intercom/api_operations/
save.rb:  18:in `create'
   /var/app/current/app/workers/
intercom_update_user.rb:  25:in `perform'
```

These are occurring on a users.create operation via an Intercom::Client.new that also contains a company - if that matters at all.

**Comment by pgaspar** [comment]
Also seeing this on `events.create`.

**Comment by choran** [comment]
Hi @pgaspar, Could you provide an example of the code/data you were using when this error occurred? i.e. you mentioned this occurred on user create when you had a company associated with the user. I would like to see what data you were setting in the user and company so I can try and recreate this and see if I can also see the error occurring? From what you said I am guessing some of the users with similar company data are being created successfully so it is not happening every time you try and create a user with company data. Similarly, if you could provide any examples of the events and tags actions you are trying it would help try and re-create it.

**Comment by Tongboy** [comment]
Hi @choran,

Subsequent reruns of the same request have always succeeded (we automatically retry with sidekiq.) Here is what our request looks like:

```
intercom = Intercom::Client.new(app_id: ENV['INTERCOM_APP_ID'], api_key: ENV['INTERCOM_API'])
intercom.users.create(
  user_id: user.id,
  email: user.email,
  name: user.name,
  signed_up_at: user.created_at.to_i,
  last_seen_ip: user.current_sign_in_ip,
  custom_attributes: {
    role: user.role_i18n
  },
  companies: [ 
    {
      company_id: company.id,
      name: company.name,
      remote_created_at: company.created_at.to_i,
      monthly_spend: spend(company),
      plan: company.stripe_plan,
      custom_attributes: {
        trial_end_date_at: company.trial_end_date,
        notice_trial_end_date_at: company.trial_end_date - 8.days,
        membership_end_date_at: company.membership_end_date,
        billable_user_count: company.billable_user_count,
        customer_count: company.customers.count,
        portal_customer_count: company.customers.portal_account.count,
        device_count: company.devices.count,
        route_count: company.routes.count,
        water_purveyor_count: company.water_purveyors.count,
        submitted_test_count: company.tests.submitted.count
      }
    }
  ]
)
```

**Comment by choran** [comment]
Hi @pgaspar,
Thanks for providing this. At the moment I cannot see what caused this, from what you are saying it sounds like it was a transient issue. If I find anything else I will let you know and if this occurs again please let us know. thanks again.

**Comment by pgaspar** [comment]
Hi @choran. I think you've been wanting to mention @Tongboy and not me.

Anyway, not sure if it helps if you try seeing the error on Intercom's logs, but if it does, one of the errors I experienced was in the Tag creation endpoint at this timestamp: `1469220776.6117082 `.

Maybe finding that 500 on the API servers will give you more insight into this. Thanks.

**Comment by choran** [comment]
@pgaspar yeah sorry for wrong mention! that does help. I will check that out.
cheers.

**Comment by choran** [comment]
@pgaspar @Tongboy 
From the timestamp I was able to find some requests in our log which received a 500 at this time. There is nothing reported on our status page for this time and I was only able to find a small amount of 500's at this time. So it was not related to general availability issues. But it was an issue on our end where we were unable to process these events for a short period of time. Thanks again for the timestamp. I will close this issue for now, but if you see these issues persist then feel free to re-open or open another issue.

**Comment by Tongboy** [comment]
@choran - shouldn't that return an Intercom::ServerError rather than an Intercom::UnexpectedErrors error?

**Comment by Tongboy** [comment]
for a few days these seem to start returning 500 errors - now we're back to receiving the unexpectederror responses but the error message body has changed.

example: Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Validation failed: Remote company has already been taken and http_code: '400'. Please contact Intercom with these details.

subsequent reruns of the same request continue to succeed

last example was right around timestamp 1470488100

**Comment by camol** [comment]
I'm getting the same error lately but with the `500` code. It happends for me on `client.post "/bulk/users", payload`. This happens for every 2-3 days for few pushes in a row. But when I retry the push on exactly the same set of data after some time (from Resque cleaner web page) it gets processed without any issues.
