### ISSUE TITLE
Inconsistent return values from #find on contacts

### ISSUE THREAD

**Issue by reidab** [intercom/intercom-ruby#271]
## Version info
- intercom-ruby version: 3.5.2
- Ruby version: 2.3.0
## Expected behavior

When finding a contact by by ID address, the client raises an `Intercom::ResourceNotFound` exception when no contact exists:

``` ruby
intercom.contacts.find(id: 1337)
=> Intercom::ResourceNotFound: Contact Not Found
```

I'd expect a similar exception when trying to find contacts by email:

``` ruby
intercom.contacts.find(email: 'test@example.com')
=> Intercom::ResourceNotFound: Contact Not Found
```
## Actual behavior

Instead, I get an empty contact object

``` ruby
intercom.contacts.find(email: 'test@example.com')
=> #<Intercom::Contact:0x007ff73a7dc5d8
     @changed_fields=#<Set: {}>,
     @contacts=[],
     @custom_attributes={},
     @pages=#<Intercom::Pages:0x007ff73a123458 @changed_fields=#<Set: {}>, @next=nil, @page=1, @per_page=50, @total_pages=0>,
     @total_count=0>
```

It seems like `#find` for contacts with an email address is behaving more like `#find_all`, per the example at https://github.com/intercom/intercom-ruby#contacts.
## Steps to reproduce
1. Attempt to find a nonexistent contact by email address

**Comment by choran** [comment]
Hi @reidab 
yeah, this can be a little confusing. 
contacts behave a little differently from users in terms of finding them. If you look at the API [docs](https://developers.intercom.io/reference#view-a-lead) to view a lead you will see that you can only search with a user_id and an id to find a single contact. Whereas to view a [user](https://developers.intercom.io/reference#view-a-user) you can use user_id or email. So email is not a method you can use to view a single contact in the same way you can view a single user.  When you use find in this manner with a contact it will act in a similar fashion to find all for contacts, i.e. it returns a list. Let me know if that makes sense?

**Comment by reidab** [comment]
That makes sense — there's another bit of inconsistency here that's closely linked, so I'll mention that as well.

If you're using `#find` on contacts and the search _does_ return results, it will return a strange `Intercom::Contact` object that contains the individual records as ruby hashes. `#find_all` returns the nicer `ClientCollectionProxy` object with the individual records correctly instantiated as `Intercom::Contact`s. It may make sense to throw an exception if `#find` is attempted on contacts with anything but `user_id` or `id` to avoid this confusing return state.

**Comment by choran** [comment]
@reidab 
I think this is the same for users as well though, i.e. find returns an "Intercom::User" object and find_all returns "Intercom::ClientCollectionProxy". Just curious why you think it is strange ... i.e. is there some attribute missing from it or is it difficult to use for you use-case? 

For now we will not add an exception for this case but I take your point. I will keep it in mind. At the very least I will see if perhaps we can try and clear up this confusion in the docs.

**Comment by reidab** [comment]
Having `#find` consistently return an `Intercom::User` or an `Intercom::Contact` and `#find_all` return an `Intercom::ClientCollectionProxy` is what I would expect. The thing that's confusing is when `#find` is used with an email address and returns an object looking like this:

````ruby
intercom.contacts.find(email: 'bob@example.com')
=> #<Intercom::Contact:0x007fa3698266d0
 @changed_fields=#<Set: {}>,
 @contacts=
  [
    {
      "type"=>"contact",
      "id"=>"...",
      [... cut for brevity ...]
    }
  ],
 @custom_attributes={},
 @pages=
  #<Intercom::Pages:0x007fa369824588
   @changed_fields=#<Set: {}>,
   @next=nil,
   @page=1,
   @per_page=50,
   @total_pages=1>,
 @total_count=1>
```

This object claims to be an `Intercom::Contact`, but has none of the expected contact attributes. It's clearly representing a collection, but doesn't respond to any of the methods that I'd expect a collection to respond to (e.g. `#first`).

To avoid breaking the promise of `#find` always returning a single record, it seems like this sort of usage (`Contact#find` by email) should either be prevented with an exception or treated as an alias to `#find_all` and return a collection proxy.

**Comment by choran** [comment]
ah, yeah, I see what you mean now. Let me look into it a little more.

**Comment by Skaelv** [comment]
It seems it's more of a confusion than an issue. It's not ideal that `find` returns an array when requesting by email but you can use  `find_all` to make your code clearer.
