### ISSUE TITLE
Impossible to list Leads after 9,999th

### ISSUE THREAD

**Issue by flood4life** [intercom/intercom-ruby#274]
## Version info

  Irrelevant, reproducible with cURL: `curl -u AUTH_TOKEN: -H 'Accept: application/json' 'https://api.intercom.io/contacts?page=201`
## Expected behavior

201th page of leads (contacts), i.e. 10,000th to 10,049th
## Actual behavior

`{"type":"error.list","request_id":"am8kvuenottnjlupq970","errors":[{"code":"parameter_invalid","message":"'page' not found on model"}]}`
## Steps to reproduce

 Attempt to get 201th page of leads (contacts) for application with 10,000 or more leads.
## Logs

One of request ids: am8kvuenottnjlupq970

**Comment by flood4life** [comment]
Something similar is happening to companies.
`curl -u AUTH_TOKEN: -H 'Accept: application/json' 'https://api.intercom.io/companies?page=200&per_page=50'` responds as usual.
`curl -u AUTH_TOKEN: -H 'Accept: application/json' 'https://api.intercom.io/companies?page=201&per_page=50'` responds with an empty list: 
`{"type":"company.list","pages":{"type":"pages","next":null,"page":201,"per_page":50,"total_pages":0},"companies":[],"total_count":0}`

**Comment by lcpriest** [comment]
I have this too and thought I was going nutty. Occurs equally with users endpoint.

This is the code that raises it I believe:
https://github.com/intercom/requisite/blob/master/lib/requisite/api_model.rb#L16

**Comment by flood4life** [comment]
@lcpriest That's not an SDK problem, it's an API problem. Users at least have beta scroll API alternative https://developers.intercom.io/reference#iterating-over-all-users, but other API endpoints are doomed to 10k limit for now.
I believe this is temporary (it's actually not the first time API does this trick, initially there was no limit, then it was 250k, then 100k, then 10k, then 100k again), but this really screws us over.
@choran are there plans for scroll APIs for endpoints other than users? It's really not cool that sometimes API just arbitrarily puts these kinds of limitations on endpoints.

**Comment by choran** [comment]
@flood4life @lcpriest At the moment we do not have immediate plans to add a scroll function for leads.
@lcpriest Can I ask what your use case is for wanting to list all of your leads? There may be a workaround depending on your use case. In many instances listing all users/leads in this manner is not required. But if we better understand the use case then it will help us plan this in our roadmap going forward.

**Comment by lcpriest** [comment]
Hi @choran, thanks for the update!

We are trying to pull out users (not leads at the moment) for a specific segment, usually the 'Active and Paying' (this tends to cut the list down to just relevant users) as we are performing some reporting on these users by product usage (which Intercom tracks very well).

Ideally, we could just listen to an event for when a user record updates, and if a user enters or exits this segment, but I don't believe that exists as of yet.

**Comment by flood4life** [comment]
@choran we are building reports for our customers, one of the reports is leads conversion, i.e., how many leads became users, hence we need full list of leads, updated every day. And for company-based reports we need full list of companies, updated every day too.

**Comment by choran** [comment]
@lcpriest you can create custom events and subscribe to them via a webhook so you are updated when some part of the user is updated. you would then be able to perform your action only on the list of users where something changed. You can find more info [here](https://docs.intercom.io/the-intercom-platform/track-events-in-intercom) Do you think that would work for you?

**Comment by lcpriest** [comment]
The data that defines the segments is a custom attribute, not an event and we may not know ahead of time what the data is - we just get told which segment to monitor and build reports on. Is there any way to create an event for when a segment changes?
  
  
  

  
  
>

**Comment by choran** [comment]
If it is a custom attribute then you should be able to create an event when that changes. You cannot do it with a segment but if you just want to check when a certain attribute is changed then creating a event for that should work. Would it work if you monitored the custom attribute instead of the segment?

**Comment by zitooon** [comment]
Hi, do you plan to support the scroll API in the intercom-ruby client ? If yes can you provide an eta ?

Thanks

**Comment by lcpriest** [comment]
@choran I'm not sure I can see how to trigger a webhook on a custom attribute changing?
<img width="340" alt="screenshot 2016-08-08 23 16 44" src="https://cloud.githubusercontent.com/assets/735593/17484788/32aa93ae-5dbe-11e6-8d0e-69f0f2eb17db.png">

Unfotunately, we don't control the Intercom install as it belongs to our customers' - we can only access what is available through the Intercom API (we can get them to create segments within Intercom)

**Comment by Skaelv** [comment]
@lcpriest there is currently no easy way to trigger a webhook on custom attribute update.

A workaround would be to create an event when this custom attribute is updated and add an event based webhook.

**Comment by lcpriest** [comment]
Even with the scroll API - does intercom only list up to 150k resources? 
I have a customer with 300k+ users. 
After the `scroll.each` has finished, I still seem to be missing a few on my end.

**Comment by flood4life** [comment]
Since leads and companies scrolls are in place now, this and #304 can be closed
