### ISSUE TITLE
Support for Rack tracker

### ISSUE THREAD

**Issue by Startouf** [intercom/intercom-ruby#289]
I just found this awesome gem [rack-tracker](https://github.com/railslove/rack-tracker) that seems to help delegate tracking to a middleware.  

I would find it awesome to provide an Intercom module for their gem. That's what I will probably end up doing since the tracking code is getting really messy on my website. I am posting here in case someone already started something with rack-tracker and would be willing to share some code.

**Comment by Skaelv** [comment]
Hey! It seems really interesting. I'd love to have this in the [intercom-ruby-app](https://github.com/intercom/intercom-ruby-app). 
 Let us know if you need anything.

**Comment by Skaelv** [comment]
I'm closing as this is not an `intercom-ruby` related issue.
