### ISSUE TITLE
Messages not respecting `from` params

### ISSUE THREAD

**Issue by thenickcox** [intercom/intercom-ruby#290]
## Version info
- intercom-ruby version: 3.5.2
- Ruby version: 2.1.1
## Expected behavior

The id of the `from` user is respected when creating a new message
## Actual behavior

The message appears from another admin user
## Steps to reproduce

Here is the code generating the message:

``` ruby
  def close_account_message
    intercom = Intercom::Client.new(app_id: Rails.application.config.intercom_app_id, api_key: Rails.application.config.intercom_api_key)
    user = User.by_organization_id(current_organization).find(params[:id])
    message = I18n.translate('settings.billing.closeaccountintercommessage', name: user.first_name)
    if user
      # InApp message from admin to user
      intercom.messages.create({
        :message_type => 'inapp',
        :body => message,
        :from => {
          :type => 'admin',
          :id => Rails.application.config.intercom_from_id
        },
        :to => {
          :type => "user",
          :user_id => user.id
        }
      })
      render 'common/success'
    else
      render 'common/error';
    end
  end
```

`Rails.application.config.intercom_from_id` points to a certain team member, but the message appears to be from another team member, suggesting that the `id` field is not being respected.

**Comment by thenickcox** [comment]
As a note, the team member it's actually using appears to be the `last_participating_admin`

**Comment by choran** [comment]
Hi, I think this may be related to the [rails](https://github.com/intercom/intercom-rails) repo rather than the ruby one? If you think this is related to a ruby issue also please reopen.
Thanks
