### ISSUE TITLE
Undefined method 'find' for admins intercom service.

### ISSUE THREAD

**Issue by JIucToyxuu** [intercom/intercom-ruby#291]
## Version info
  - intercom-ruby version: 3.5.4
  - Ruby version: 2.1.2

## Expected behavior
 Should find admin by id.
## Actual behavior
  raised error
`NoMethodError Exception: undefined method 'find' for #<Intercom::Service::Admin:XXX>`

## Steps to reproduce
 1. intercom_client = Intercom::Client.new(app_id: ***, api_key: ***)
 2. intercom_client.admins.find(:id => '1')

**Comment by Skaelv** [comment]
Hi @JIucToyxuu,
I was able to reproduce your issue on `3.5.4` but it's been fixed on `3.5.7`.
Update your version of intercom-ruby and you'll be fine 👍
