### ISSUE TITLE
Scroll already exists

### ISSUE THREAD

**Issue by cimm** [intercom/intercom-ruby#292]
We are using the `intercom-ruby` v3.5.4 gem with the [new scroll API](https://developers.intercom.com/reference#iterating-over-all-users) to loop over all our users, if something breaks during the scroll you get the following error when you restart it:

```
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: scroll already exists for this app and http_code: '400'. Please contact Intercom with these details.
```

Waiting a few minutes does fix the problem so I guess it's a open request on Intercom's side that needs some time before it times out and can be reused again. From the documentation:

> Each app can only have 1 scroll open at a time. You'll get an error message if you try to have more than one open per app.

This is particularly annoying during the development phase as you can't quickly try fix something and run it again.

Is there a way to expire a `scroll` and generate a new one?

**Comment by Skaelv** [comment]
There is no way to generate a new scroll param or to expire it (yet). You'll have to wait one minute.

**Comment by ssjunior** [comment]
+1 to have a way to expire it before 1 minute

**Comment by armandomiani** [comment]
When you don't pass a scroll_param, it could create a new one and expire the other existing scrolls 

6 hours more to develop using scroll :sweat_smile:

**Comment by evyasafhouzz** [comment]
I keep getting the message: '**scroll already exists for this app**' no matter much time has been a pass.
