### ISSUE TITLE
sending a message from an email contact requires user?

### ISSUE THREAD

**Issue by riffraff** [intercom/intercom-ruby#295]
I am confused as to how I'm supposed to send feedback from an anonymous user identified only by an email.
## Version info
- intercom-ruby version: 3.2.0
- Ruby version: 2.2.5
## Expected behavior

I expect to be able to send a message from an unknown user identified only by email
## Actual behavior

Intercom complains the user doesn't exist
## Steps to reproduce
1. `c=Intercom::Client.new(...)`
2. `c.messages.create(from: {type: 'contact', email: 'me@example.com'}, body: 'halp')`
3. result: `Intercom::ResourceNotFound: User Not Found`

So what should I do if I just want to send a message from an passer by? 
Do I need to create a new Lead with this email first? 
Shouldn't this happen automatically?

Thanks in advance for any help.

**Comment by Sylvain** [comment]
From what I see, you want to use Contacts https://github.com/intercom/intercom-ruby#contacts
You create a contact by the email you have : 
`contact = intercom.contacts.create(email: "some_contact@example.com")
`
You can then send message from a contact:
```
intercom.messages.create({
  :from => {
    :type => "contact",
    :id => "536e5643as316c83104c400671"
  },
  :body => "halp"
})
```

**Comment by raldred** [comment]
Anyone arriving here. This doesn't work.
Creating a contact is fine, but intercom.message.create fails with `uninitialized constant SerializableHash`

**Comment by choran** [comment]
Hi @riffraff, 
Just wondering if you are still having issues with this? The response above should work. You can use the ID from the URL or the user_id (which for leads is auto created also) these should help you identify the lead. But this does assume that you have a lead already. There has to be some entity in the app to represent the person sending the message. So you could create this as suggested above first. 
Will close for now but let me know if you are still having issues

**Comment by riffraff** [comment]
I have since removed this from the app altogether, so I can't tell you, but it's fine to close it for me, thanks for your time.
