### ISSUE TITLE
Add scroll support for companies

### ISSUE THREAD

**Issue by thomasdziedzic** [intercom/intercom-ruby#304]
## Version info
  - intercom-ruby version:  3.5.9
  - Ruby version: 2.3.1

## Expected behavior
Able to iterate through all the companies.

## Actual behavior
Iterating through all the companies throws error after a couple thousand companies.

## Steps to reproduce
 1. have an account with > 6000 companies.
 2. iterate through all companies using `client.companies.all.each do |company| ... end`

## Logs
```
/Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/request.rb:143:in `raise_application_errors_on_failure': page limit reached, please use scroll API (Intercom::BadRequestError)
        from /Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/request.rb:94:in `parse_body'
        from /Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/request.rb:70:in `block in execute'
        from /Users/thomas/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
        from /Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/request.rb:65:in `execute'
        from /Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/client.rb:111:in `execute_request'
        from /Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/client.rb:88:in `get'
        from /Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/client_collection_proxy.rb:22:in `block in each'
        from /Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/client_collection_proxy.rb:20:in `loop'
        from /Users/thomas/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.9/lib/intercom/client_collection_proxy.rb:20:in `each'
        from bin/main.rb:39:in `<main>'
```

**Comment by thomasdziedzic** [comment]
After reviewing the possibility of adding this functionality into the ruby library, I realized that the api documentation doesn't list out companies as having a scroll api.

https://developers.intercom.com/reference#list-companies

**Comment by swordfish444** [comment]
This can now be addressed https://app.intercom.com/a/changes/431

**Comment by lcpriest** [comment]
Merged here https://github.com/intercom/intercom-ruby/pull/320

**Comment by choran** [comment]
Just closing this since scroll is available for users, leads and companies now.
I updated the readme to reflect this
