### ISSUE TITLE
Company plan

### ISSUE THREAD

**Issue by tilsammans** [intercom/intercom-ruby#306]
`intercom-rails` provides a handy company `plan=` method to set the company's plan. But this is not available in `intercom-ruby`. There seems to be some magic involved with the `self.config_delegator` method, but I'm not sure what's the approach here.

I'd like to set the company's plan in `intercom-ruby` as well, or at least have a documented means of sending this information to the API. Currently the `plan` method is not allowed in `intercom-ruby`.

## Version info
  - intercom-ruby version: 3.5.3
  - Ruby version: 2.3.1

## Expected behavior
I should be able to update a company's plan using the Ruby intercom library.

## Actual behavior
I'm being told `Intercom::BadRequestError: found unpermitted parameter: plan`.

**Comment by choran** [comment]
HI @tilsammans,
Thanks for the query ... I think there may be some confusion about the plan attribute. I think this may have changed hence the confusion. The plan attribute is now a sting (I think it was an object originally). However, if you retrieve it you get two fields, id and name, but you can only actually set the name. So for example this works

company = intercom.companies.find(company_id: "10")
company.plan = "PLAN4"
intercom.companies.save(company)
puts(company.plan.inspect)
#<Intercom::Plan:0x0000000821a8b8 @id="133960", @changed_fields=#<Set: {}>, @name="PLAN4">

So you should be able to set it for the plan in this way. Let me know if you are able to set it a different way via rails or if you are seeing that it is not a string. If you have some example code of it working differently please let me know and I can try and reproduce that code.
I will close this for now but please re-open if you think I misinterpreted your query

**Comment by tilsammans** [comment]
Hi @choran appreciate the update. Setting the plan as a string is totally fine.

I'll see if I can make it work using the new version, if not, I'll circle back here.
