### ISSUE TITLE
Using tags= on company leads to invalid payload

### ISSUE THREAD

**Issue by aldhsu** [intercom/intercom-ruby#307]
## Version info
  - intercom-ruby version: 3.5.2
  - Ruby version: 2.3.1p112

## Expected behavior

Company model has a `tags=` method. If its not supported it probably shouldn't appear.

## Actual behavior
API does not allow for updating tags along with the company model. Company now cannot be saved by calling `#save(company)`. Rejects with `Intercom::BadRequestError: bad 'tags' parameter`.

## Steps to reproduce
 1. Retrieve company
 2. Modify tags with `#.tags = []`
 3. Attempt to save company with `#.save(company)`

**Comment by choran** [comment]
Hi @aldhsu 

Thanks for the query, you can set the tags for companies via the tag method.
The tag on the companies model allows you to check what tags are then set for that company.
For example

```
company = intercom.companies.find(company_id: "10")
puts(company.tags) #This will show the tags for the company
#You can then use tags to tag the company
tag = intercom.tags.tag(name: 'tag2', companies: [{company_id: "10"}])
puts(company.tags)
```

Let me know if that does not work for you.
Thanks and sorry for the delay in getting back
