### ISSUE TITLE
'Error: unknown keyword: token' when starting new client with a PAT instead of API Key

### ISSUE THREAD

**Issue by briemarie** [intercom/intercom-ruby#308]
## Version info
  - intercom-ruby version: 3.5.9
  - Ruby version: 2.1.5p273

## Expected behavior
With the deprecation of API keys, I expect that the new client code provided in README (and also on this page in the Intercom API docs https://developers.intercom.com/reference#using-personal-access-tokens) will start the intercom client using the personal access token.

## Actual behavior
Error: unknown keyword: token

access_token = Rails.application.secrets.ic_pat
intercom = Intercom::Client.new(token: access_token)

* I even tried to set it with this syntax, but receive the same error 
intercom = Intercom::Client.new(:token => access_token)

* When I print out access_token, it is the correct token

## Steps to reproduce
 1. Activate a call to the Intercom API

**Comment by Skaelv** [comment]
Hey @briemarie. 
I wasn't able to reproduce this issue with `ruby 2.1.5` and `intercom 3.5.9`.
We've been using access tokens in this client for a while now so it should be working fine.

I've downgraded intercom to 3.1.0 and I get `ArgumentError: unknown keyword: token`

Do you still experience this issue ?

**Comment by briemarie** [comment]
Hey @Skaelv I'm closing this. I made the mistake of thinking that updating the gem and Gemfile was picked up in my docker image, but it was not, and was still running the gem with the older version. I've rebuilt and it is all working now. Thanks for the response!
