### ISSUE TITLE
Gem fails to install on Ruby 2.4 due to dependency on son 1.8.3

### ISSUE THREAD

**Issue by nburns** [intercom/intercom-ruby#312]
## Version info
  - intercom-ruby version: 3.5.9
  - Ruby version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

## Expected behavior
I expect to be able to run `gem install intercom` and have the gem be installed

## Actual behavior
When I run `gem install intercom` the gem fails to install because json 1.8.3 fails to install

## Steps to reproduce
 1. install ruby 2.4
 2. try to install the intercom gem

## Logs
https://gist.github.com/nburns/84d4c8a7b9c32133a12f85acd34e7a18

**Comment by Empact** [comment]
@nburns FYI this is fixed in master https://github.com/intercom/intercom-ruby/commit/ca59f04c7ed4bb9073198335ddd99a32e7e3f332

**Comment by pboling** [comment]
@Empact any idea when a new release will be out with the fix?  For now I will point to git master.

**Comment by nburns** [comment]
Thanks for the info, I'd like to be able to pin a version in my gemfile, is there a corresponding version number I can use?

**Comment by Empact** [comment]
I'm not a committer, just an interested observer asking the same questions.

**Comment by Skaelv** [comment]
Hey guys! I just bumped the version so this should be fixed on `3.5.10`
