### ISSUE TITLE
Bulk update users doesn't seem to work

### ISSUE THREAD

**Issue by davidpdrsn** [intercom/intercom-ruby#316]
## Version info
  - intercom-ruby version: 3.5.9
  - Ruby version: 2.3.0

## Expected behavior

The following code should update the custom attributes of the user.

```ruby
intercom.users.submit_bulk_job(create_items: [{user_id: user.id}, {"testing" => "foobar"}])
```

## Actual behavior

It errors with a message of 

```json
{
  "errors": [
    {
      "code": "media_type_not_acceptable",
      "message": "The Accept header should send a media type of application/json"
    }
  ],
  "type": "error.list"
}
```

**Comment by snkashis** [comment]
Has there been any movement on this topic? An upsert capability on the user model would be really helpful I think.
