### ISSUE TITLE
Intercom::UnexpectedError: The error of type '' is not recognized. 

### ISSUE THREAD

**Issue by bcackerman** [intercom/intercom-ruby#323]
```
[6] pry(main)> @intercom.contacts.find(email: @email_address)
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Not authorized to access resource and http_code: '401'. Please contact Intercom with these details.
from /Users/bruceackerman/.rvm/gems/ruby-2.3.1/gems/intercom-3.5.12/lib/intercom/request.rb:155:in `raise_application_errors_on_failure'
```

Getting this error, any idea?

## Version info
  - intercom-ruby version: 3.5.12
  - Ruby version: 2.3.1

**Comment by Aslonski** [comment]
@bcackerman Replied to your question on this issue in Intercom. 👍

**Comment by jackcasey** [comment]
What was the fix? ><; We've just started hitting this and not sure why. @Aslonski

**Comment by conarro** [comment]
@jackcasey not sure what calls you're making, but if you're trying to use certain endpoints you'll need to request access to extended scopes:
https://developers.intercom.com/docs/personal-access-tokens#section-extended-scopes

Just ran into this and got it pushed through via Intercom support. Hope this helps!
