### ISSUE TITLE
`find_all` does not find multiple users with same email address

### ISSUE THREAD

**Issue by m-o-e** [intercom/intercom-ruby#326]
## Version info
  - intercom-ruby version: 3.5.9
  - Ruby version: 2.3.3p222

## Expected behavior

Return all users that match a given email address.

## Actual behavior

`Intercom::MultipleMatchingUsersError: Multiple existing users match this email address xx@example.com - must be more specific using user_id`

## Steps to reproduce

`intercom.users.find_all(type: 'users', email:'xx@example.com').each_with_index { |u,i| p u }`

## Question

How to fetch all users that match a given email address **without** providing any
additional information?

The intercom web-interface (search) can do it, but how is it done via the API?
We don't know any userids, only the email address.

**Comment by AGarrow** [comment]
I'm having the same issue :/

**Comment by KJTsanaktsidis** [comment]
This is completely bananas - your data suddenly becomes unqueryable in this dimension as soon as you get a single dup in Intercom...

**Comment by choran** [comment]
Hi all, 
Yeah, this is a restriction at the moment with the API, i.e. it looks for a specific match so if you have multiple emails it will return the error. So it is not a restriction with the SDK as such. We are aware of this issue and thanks for bringing it up. It is frustrating given that you can identify duplicates via the web UI. We are trialling something internally to see if it resolves this issue to allow you search for users with multiple similar attributes such as email. I cannot provide an ETA at the moment but we if it works we will update the API which should resolve this issue.
I will leave this issue open as it may be something other people want to comment on even for suggestions of how they would like it to work as well

**Comment by rubendinho** [comment]
Hi there - just wanted to see if there's an update to this?  We are also seeing occasional duplicate records making it impossible to work with the API for those users.

**Comment by davidlaprade** [comment]
+1

**Comment by dstotz** [comment]
+1

**Comment by choran** [comment]
Hi @rubendinho .. at present we do not have an update on an ETA for this feature.
Thanks for the feedback here, it helps us understand its impact and we are looking to see how and when we can address this. I will provide an update when I have more information on this.

**Comment by m-o-e** [comment]
Just want to add that we consider this a bug, not a feature.
A portion of our users is inaccessible through the API.

**Comment by choran** [comment]
np, thanks for noting that. we do understand that this is a restriction for a number of use cases so we are tacking it as such, i.e. something that needs to be resolved.

**Comment by a17levine** [comment]
+1

**Comment by choran** [comment]
👍

**Comment by jaGarcia** [comment]
+1

**Comment by choran** [comment]
👍 thanks for this, unfortunately at the moment we do not have an update on this but the appreciate the feedback and hopefully we will get to this as soon as we can

**Comment by molesky** [comment]
+1

**Comment by rogerkerse** [comment]
+1 Having the same problem

**Comment by theandrewykim** [comment]
Hey all - as a heads up, as Cathal mentioned - this issue is best served as a discussion for how this is being handled by you all. Since the behavior you're running into is a result of the behavior of the actual API (for which this repo is just a wrapper for) - your best bet would be to give feedback directly by writing into our messenger, or emailing team@intercom.io . We really do appreciate the feedback 👍

**Comment by choran** [comment]
As noted, this is an issue with the API which we will be addressing in the near future, it is on our short term plan. So I will close this issue as it is not an SDK issue and something we are addressing on our API. we can then look into if there is any issue once we make the change on the API

**Comment by davidlaprade** [comment]
Hey @choran it looks like the new version of the Intercom API (v1.1) has support for the feature that we have in mind here. I'm looking at the [List By Email](https://developers.intercom.com/intercom-api-reference/reference#list-by-email-1) functionality.

> You can list users by email to find all users with the same email address. [...] Returns a pageable list of users.

Do you plan to support the new version of the API any time soon? Would you be open to a PR that introduced this functionality?

Thanks!

**Comment by choran** [comment]
Its a good point that we should have noted this in the README, I have updated with the example above and a note on the version change needed 👍
