### ISSUE TITLE
No method `find_all` for events

### ISSUE THREAD

**Issue by Startouf** [intercom/intercom-ruby#327]
## Version info
  - intercom-ruby version: intercom-3.5.4
  - Ruby version: 2.3

The Intercom gem does not provide a Ruby interface for the Intercom events

```
intercom.events.find_all("type" => "user", "intercom_user_id" => "123abc")
# => NoMethodError: undefined method `find_all' for #<Intercom::Service::Event
```

**Comment by choran** [comment]
Hi, I am not sure if this was a new feature added or not but it seems to work for me
events = intercom.events.find_all("type" => "user", "intercom_user_id" => "596f35f744c4c5f0cd30c8ef")
events.each { |event| puts(event.event_name) }

I will close this for now but if you cannot get this to work please let me know
