### ISSUE TITLE
UnexpectedError is thrown instead of AuthenticationError when access_token is invalid

### ISSUE THREAD

**Issue by raldred** [intercom/intercom-ruby#329]
Fairly minor but it currently throws `UnexpectedError` instead of `AuthenticationError` when access_token is invalid.

## Version info
  - intercom-ruby version: 3.5.12
  - Ruby version: 2.4.0

## Expected behavior

It should probably raise `AuthenticationError`

## Actual behavior

Raises `UnexpectedError`

## Steps to reproduce
 1. instantiate a client with an invalid access token
 2. make a request for something eg. intercom.users.create
 3. see UnexpectedError raised.

## Logs

```
Intercom::UnexpectedError The error of type '' is not recognized. It occurred with the message: Unauthorized and http_code: '401'. Please contact Intercom with these details.
```

**Comment by Skaelv** [comment]
Will be fixed in `3.5.15`
