### ISSUE TITLE
Convert lead to user doesn't work

### ISSUE THREAD

**Issue by jameslieu** [intercom/intercom-ruby#330]
Convert contact to users doesn't seem to work as expected.

## Version info
  - intercom-ruby version: 3.5.11
  - Ruby version: 2.1.7

## Expected behaviour
When calling the `.contacts.convert(contact, user)` method
It should convert the lead to a user on Intercom

## Actual behaviour
The lead is not converted 

## Steps to reproduce
 1. Create a Lead on intercom that has an email address
 2. Make sure that there is not a user which has the same email address 
 3. Call `intercom.contacts.convert(contact, nil)` (`nil` because the intercom user does not exist)
 3. See that a new user with that email has not been created and the lead has not been deleted

---

It doesn't seem to work at all. Though I've found a unusual way around it.

When calling `intercom.contacts.convert(contact, nil)` it does return an `Intercom::User` object (though it doesn't seem to create the User on Intercom itself) so I assign it to a variable `user`. 

I've tried to then call `.save` to this user to attempt to create it. Which returns a error:

```
intercom.users.save(user)
#=> Intercom::ResourceNotFound: User Not Found
```

However, if I use this object to call `intercom.contacts.convert(contact, user)` a second time. It returns the user object again (so I assign this to `user2`).
The user has not been created this time either but the lead has been deleted

Then call `intercom.users.save(user2)`. 

The user is now created.

**Comment by dustinbrownman** [comment]
+1 to this issue.

Also, when the user actually gets created in Intercom, it has lost all of its Lead attributes (like "name"). This means that even with the workaround outline above we're not really converting leads to users, but rather deleting a lead and creating a totally new user.

**Comment by dustinbrownman** [comment]
It looks like this is an API problem. I'm getting the same behavior when using curl to try and convert leads.

**Comment by dustinbrownman** [comment]
Just tested again today after hearing that they had fixed the endpoint. Indeed I was able to convert a Lead to a User using `curl`. Doing this using the Ruby SDK still doesn't work, however.

**Comment by dustinbrownman** [comment]
I think I may have found a solution for this. The problem stems from passing `nil` in for the user. I'd expect the SDK to work that way, but since it doesn't, here's what I tried (and it worked):

```ruby
intercom.contacts.convert(lead, Intercom::User.new(email: email))
```

Another solution would be to go ahead and create the user in intercom, then use the convert function to merge in all the lead attributes:

```ruby
user = intercom.users.create(email: email)
intercom.contacts.convert(lead, user)
```

**Comment by mmartinic** [comment]
@dustinbrownman the first example you have is the correct way to do it
```
intercom.contacts.convert(lead, Intercom::User.new(email: email))
```
Identifiers in the new User object will be used to try to find an existing user. If the user is not found it will convert lead to a user. It behaves the same as if you use curl directly on the API
https://developers.intercom.com/v2.0/reference#convert-a-lead

Validation was added to API so it returns 400 if user identifiers are not present in the request, so `intercom.contacts.convert(contact, nil)` will now fail.

**Comment by markalanevans** [comment]
@mmartinic if a user is on my site as a visitor, then we chat w/ them and they become a lead, we had a few custom pieces of data to that lead via the api. Sport, Age, ..     At some point they come to our site and signup.

The site uses the javascript sdk and we also use api.

what unique thing must happen for that lead to now show up as a user and no longer as a lead?

This piece of docs
" (https://www.intercom.com/help/faqs-and-troubleshooting/your-users-and-leads-data-in-intercom/how-do-visitors-leads-and-users-work-in-intercom)

**When does a lead become a user?**
A lead becomes a user when they sign up to your product, or log into an existing account. All of the information and conversations you've had with them remain in their user profile. 
"

Isn't really clear about how a lead becomes a user and is no longer a lead. Can you clarify this?
