### ISSUE TITLE
401 when making bulk delete requests

### ISSUE THREAD

**Issue by rossgeesman** [intercom/intercom-ruby#336]
## Version info
  - intercom-ruby version: 3.5.12
  - Ruby version: 2.3.4

## Expected behavior
We run a daily cron job to delete our inactive users from Intercom. We do this with the bulk job endpoint using the Ruby client and have done this for a long time with no issues. We recently switched to using the access token so we would expect the same results.

## Actual behavior
The API returns errors: `The error of type '' is not recognized. It occurred with the message: Unauthorized and http_code: '401'. Please contact Intercom with these details.` I already talked to a support engineer about this and they assured me we are initializing the client with the access token the right way. I'm able to get everything to work in our test sandbox just fine so I'm not sure what could be causing the issues in production.

## Steps to reproduce
```ruby
#1 Initialize an instance of the api client with our access token. 
INTERCOM_API = Intercom::Client.new(token: Settings.intercom.access_token)
#2. First build an array of all of the users we wish to delete. They look like this:
data = [{user_id: <USERID>, email: <EMAIL>}]
#3. Send a request to the API (we limit each request to 100 users)
job = INTERCOM_API.users.submit_bulk_job(delete_items: data )
#4. Each call to this endpoint usually returns the details of a job. We are getting 401.
```

**Comment by Skaelv** [comment]
Hi @rossgeesman ! This is strange indeed.
Some API requests require extended access token scope which could explain why you are seeing this behavior if you have a standard access token. 
Make sure your access token's permissions are enough for what you are trying to achieve by visiting the [developer hub](https://app.intercom.com/developers/_)

**Comment by rossgeesman** [comment]
I thought that might be the case and asked when I talked with a support engineer before but they didn't seem to think it was an issue. I went ahead and requested increased permissions, hopefully that helps. Thanks
