### ISSUE TITLE
Error despite catching Intercom::IntercomError

### ISSUE THREAD

**Issue by morgler** [intercom/intercom-ruby#340]
## Version info
  - intercom-ruby version: 3.5.5
  - Ruby version: 4.2.8

## Expected behavior
If catching `Intercom::IntercomError`, no exception should be raised if Intercom event tracking fails. This is important, as event tracking is not critical. A failure to track an event should **not** halt the entire application, but fail silently in this case.

## Actual behavior
When turning off the internet connection, I get a 

```
SocketError at /date_inquiries
getaddrinfo: nodename nor servname provided, or not known
```

from `@intercom.events.create` where

```
@intercom ||= Intercom::Client.new(token: ENV['INTERCOM_ACCESS_TOKEN'])
```

I would assume that catching the Intercom exception, no error would be raised if tracking fails. Here is the full code of my tracking call:

```
begin
        @intercom ||= Intercom::Client.new(token: ENV['INTERCOM_ACCESS_TOKEN'])
        @intercom.events.create(
          event_name: name,
          created_at: Time.now.to_i,
          user_id:    current_user.id,
          metadata: metadata
        )
      rescue Intercom::IntercomError => e
        # Don't fail just because event tracking for Intercom failed
        logger.warn e.message
      end
```

## Steps to reproduce
 1. Catch all `Intercom::IntercomError`s around a call to `events.create` 
 2. Turn off your internet connection
 3. Watch the above SocketError be raised.

## Logs
```
Completed 500 Internal Server Error in 129ms (ActiveRecord: 13.7ms)

SocketError - getaddrinfo: nodename nor servname provided, or not known:
  /Users/morgler/.rbenv/versions/2.2.6/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
  /Users/morgler/.rbenv/versions/2.2.6/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
  /Users/morgler/.rbenv/versions/2.2.6/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
  /Users/morgler/.rbenv/versions/2.2.6/lib/ruby/2.2.0/net/http.rb:878:in `connect'
  /Users/morgler/.rbenv/versions/2.2.6/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
  /Users/morgler/.rbenv/versions/2.2.6/lib/ruby/2.2.0/net/http.rb:852:in `start'
  intercom (3.5.5) lib/intercom/request.rb:65:in `execute'
  intercom (3.5.5) lib/intercom/client.rb:111:in `execute_request'
  intercom (3.5.5) lib/intercom/client.rb:92:in `post'
  intercom (3.5.5) lib/intercom/api_operations/save.rb:26:in `save'
  intercom (3.5.5) lib/intercom/api_operations/save.rb:18:in `create'
  app/controllers/application_controller.rb:84:in `track_intercom_event'
```

**Comment by apraditya** [comment]
In my case it happens on `Intercom::ResourceNotFound` error.

**Comment by choran** [comment]
HI @morgler,
I would have thought most people would want to raise an exception when submitting events has failed. But in any case, maybe I am missing something, but could you perform a general exception catch to catch all/other errors if you did not want it to stop?
So you could rescue your specific errors and then fall through to the more general ones?
Would that work or do you not want to have any general exception catching (i know its generally not recommended but was just wondering would it solve your issue here)?
just wanted to clarify if that was something you tried or whether this was something you were specifically avoiding

**Comment by morgler** [comment]
Thanks @choran . That's probably what I have to (and want to) do: catching all errors. This way, if anything fails during creating or sending an Intercom event, it will not halt my application.

To me, Intercom events are a nice reporting add-on for my customer service, but they're not critical to the app itself. It's like if Google Analytics would fail to count some page views – not nice, but it should not affect my users by halting the app. For different use cases, expectations might be different.

**Comment by choran** [comment]
Np @morgler, yeah, like you said, I guess it does depend on the use case in terms of the expectations. For now I will close this but feel free to re-open if you feel there is anything else you would like clarified
