### ISSUE TITLE
Add documentation for bulk operations

### ISSUE THREAD

**Issue by Draiken** [intercom/intercom-ruby#343]
I've used bulk operations before with raw HTTP requests and I'm now in the process of updating the Intercom gem to the latest version.

However even tho on the `changes.md` I see the Bulk API was added, there is no documentation for it whatsoever both on the gem or the API reference website.

I'm basically going to have to read the gem's code and test it by hand because there's no way for me to know if I'm doing the right thing at this point.

Not to mention there are so many broken links between all the documentation pages, but I guess that's out of scope for this particular matter...

**Comment by Skaelv** [comment]
Hi @draiken, thanks for bringing that up. We’d like to take some time to reconsider this part of our API, make it a little more developer friendly which is why we decided to remove this section from the doc at the moment.

**Comment by choran** [comment]
Hi @Draiken, 
As in the previous response, we are reviewing our bulk APIs at the moment so have removed them from our main API doc as well so there is no documentation for them at present. We are still supporting them but not advocating customer use them and instead use the regular API as this is as efficient as the bulk for all tasks. We will provide an update when we have competed the review and decided the best approach for these in future
Thanks and I will close this for now
