### ISSUE TITLE
Uninitialized constant Intercom::BlockedUser

### ISSUE THREAD

**Issue by P9GIT** [intercom/intercom-ruby#346]
Wrong constant is used when raising a blocked user error.

Error class raised:
https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/request.rb#L147

Error class def:
https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/errors.rb#L58

## Version info
  - intercom-ruby version: 3.5.16
  - Ruby version: 2.2.5

## Expected behavior
Raise Intercom::BlockedUser**Error**

## Actual behavior
Attempts to raise Intercom::BlockedUser

## Steps to reproduce
 1. Perform e.g. a update on a blocked user
 2. Observe breakage with below exception 

## Logs
uninitialized constant Intercom::BlockedUser
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.16/lib/intercom/request.rb:147:in `raise_application_errors_on_failure'

**Comment by Skaelv** [comment]
Hey! 
Thanks for lettings us know. This has just been fixed in `3.5.17`.
