### ISSUE TITLE
on Ruby 1.9.3

### ISSUE THREAD

**Issue by steverob** [intercom/intercom-ruby#347]
I'm trying to use this with a Rails project on ruby 1.9.3. We cannot schedule a Ruby upgrade any time soon :( And unfortunately intercom has changed its authentication methods so older version of this gem is also unusable.

Is there any possible way I can interact with Intercom's REST API from a Ruby 1.9.3 based Rails app? Thanks a lot.

**Comment by choran** [comment]
Hi @steverob 
Not 100% sure about some of the rails restrictions but with older ruby version I thought you should still be able to use the API key, password format with your access token. i.e. set the access token as your key and then leave your password empty string.
That should work unless I am missing something.
If you have a rail specific issue it would be better to open it in the rail repo for from context there
In the meantime I will close this but, like I said, if i am missing something about older ruby versions let me know. i.e. what specific authentication method change are you referring to
Thanks
Cathal
