### ISSUE TITLE
scroll parameter not found

### ISSUE THREAD

**Issue by swordfish444** [intercom/intercom-ruby#348]
## Version info
  - intercom-ruby version: 3.5.16
  - Ruby version: 2.1.0

## Expected behavior
When iterating on a resource using `scroll.each` and hitting the rate-limit delay, the scroll param should extend it's timeout duration for any delays encountered.

## Actual behavior
While scrolling, subsequent processing of the results triggers the Intercom api rate-limit delay and the scroll param times out by the time processing resumes.

## Steps to reproduce
 1. Add 200+ companies to your Intercom account
 2. Run the following in rails console

```
intercom.companies.scroll.each_slice(100) do |companies|
  500.times do |n|
    begin
      intercom.counts.for_app
    rescue Intercom::RateLimitExceeded
      sleep (intercom.rate_limit_details[:reset_at] - Time.now.utc).ceiling
      retry
    end
  end
end
```

## Logs
```
Intercom::ResourceNotFound: scroll parameter not found
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/request.rb:149:in `raise_application_errors_on_failure'
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/request.rb:94:in `parse_body'
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/request.rb:70:in `block in execute'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/request.rb:65:in `execute'
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/client.rb:111:in `execute_request'
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/client.rb:88:in `get'
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/scroll_collection_proxy.rb:41:in `block in each'
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/scroll_collection_proxy.rb:37:in `loop'
	from /var/www/shared/bundle/ruby/2.1.0/gems/intercom-3.5.16/lib/intercom/scroll_collection_proxy.rb:37:in `each'
	from (irb):7:in `each_slice'
	from (irb):7
	from /var/www/shared/bundle/ruby/2.1.0/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
	from /var/www/shared/bundle/ruby/2.1.0/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
	from /var/www/shared/bundle/ruby/2.1.0/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'2.1.0
```

**Comment by swordfish444** [comment]
@Skaelv can you take a look at this issue please

**Comment by choran** [comment]
Hi @swordfish444,
I can see how the scroll.each would timeout since it just constantly calls the scroll endpoint. We did update our rate limits to check at intervals of 10 seconds rather than 60 so I can see how this would have impacted the scroll.each. The rate limit itself is unchanged, its just that we evaluate it now over 10 sec rather than 1 min which encouraged more spiky behaviour.
But I would have thought you should be able to use scroll.next to control the timeout.
The timeout should be 1 min per request ... so once you get a new scroll parameter you have 1 minute to use that. if you get a timeout and retry in 10 secs then you should get the next scroll param and that should reset the timeout to 1 min.
Have you tried to use the scroll.next example and if so do you experience the same issue?

**Comment by choran** [comment]
Hi @swordfish444 
Just wondering if you had any update on this? 
I will close this issue in the meantime but if you do have an update please re-open
Thanks
Cathal

**Comment by panser** [comment]
have the same issue
`
io.intercom.api.NotFoundException: scroll parameter not found
	at io.intercom.api.HttpClient.throwException(HttpClient.java:207)
	at io.intercom.api.HttpClient.handleError(HttpClient.java:169)
	at io.intercom.api.HttpClient.runRequest(HttpClient.java:155)
	at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:110)
	at io.intercom.api.HttpClient.get(HttpClient.java:86)
	at io.intercom.api.HttpClient.get(HttpClient.java:82)
	at io.intercom.api.DataResource.scroll(DataResource.java:75)
	at io.intercom.api.ScrollableUserCollection.scroll(ScrollableUserCollection.java:11)

`

use
`
compile group: 'io.intercom', name: 'intercom-java', version: '2.8.0'
`
