### ISSUE TITLE
Raise named exception when attemping mailing an unsubscribed user

### ISSUE THREAD

**Issue by P9GIT** [intercom/intercom-ruby#349]
Hi.

Sometimes we get this exception from the Intercom API where a user has unsubscribed from mails from our Intercom account when our app tries to send critical system mails. 
Unfortunately it is not possible in Intercom's unsubscribe feature to differentiate between e.g. news letters and critical system mail notifications to users. All mails are blocked. 
Being able to block all mail is of course a good feature for the end user to protect himself, but some of our active customers simply wish to unsubscribe from our news letters and in the consequence this will also block important system mails (that they with all probability DO want to and SHOULD receive).

In any case, the current behavior makes it hard to catch the error when a mail is attempted to be sent to a user that has unsubscribed from emails. This involves a not so pretty reg-ex'ing the error text.

## Version info
  - intercom-ruby version:  3.5.16
  - Ruby version: 2.2.5

## Expected behavior

Either:
raise exception e.g. "UnsubscribedMailError" to fail graciously
OR preferred:
allow more fine grained unsubscription feature to allow some mails to be sent, e.g. critical system mails.
We use Intercom for sending important mails such as warnings about expiring credit cards and changes to user's account settings and subscriptions.

## Actual behavior

Intercom::UnexpectedError is raised.

## Steps to reproduce
 1. Unsubscribe a user from receiving emails
 2. Attempt to send e.g. a admin initiated mail to the user
 3. Observe Intercom::UnexpectedError is raised

## Logs

An Intercom::UnexpectedError occurred in background at 2017-07-07 23:00:20 UTC :

  The error of type '' is not recognized. It occurred with the message: This user is unsubscribed from emails and http_code: '403'. Please contact Intercom with these details.
   /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.16/lib/intercom/request.rb:94:in `parse_body'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.16/lib/intercom/request.rb:70:in `block in execute'
  /usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:853:in `start'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.16/lib/intercom/request.rb:65:in `execute'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.16/lib/intercom/client.rb:111:in `execute_request'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.16/lib/intercom/client.rb:92:in `post'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.16/lib/intercom/api_operations/save.rb:27:in `save'
  /var/www/portal/vendor/bundle/ruby/2.2.0/gems/intercom-3.5.16/lib/intercom/api_operations/save.rb:19:in `create'

**Comment by choran** [comment]
Hi @P9GIT,
Just to clarify, you are referring to the unsubscribe option from the product, i.e. when sending manual or automated campaign emails via the web ui?
So you are sending these out and when people unsubscribe from these campaigns for example, you are then unable to send them emails via the API?
If you got a specific error you would still be unable to send them the email via the API if they unsubscribed? I am just trying to understand how the specific error would help in this case

**Comment by P9GIT** [comment]
Hi @choran 

Fair questions.

Yes, we send mails (news letter etc) from the campaigns (where users can unsubscribe) but we also send important system and security notification mails (e.g. change of billing email or subscription) through the API as an "Admin Initiated Conversation" (with the intent to keep all our user conversations in one place).

If I could get a specific unsubscribe error it would be clearer and easier in the code to catch these situations and even communicate the unsubscribed state back to the other part of our system.

We can of course just stop using Intercom to send security and system notifications for good which would end this matter, but as stated above we like the idea promoted by Intercom to have all conversations in one place.

Regards,
Thomas.

**Comment by choran** [comment]
Hi @P9GIT 
I am not 100% sure what scope we have in the unsubscribe options from our campaigns. One thing you could do there is check in with our CS team. They might have some other options in terms of your use case for unsubscribing. They would have dealt with more of the unsubscribe options from the product side. 
I am not 100% sure what scope we have on the unsubscribing errors. But I can try and check it out a bit on the API side and get back to you with confirmation of whether there is anything we can do here

**Comment by P9GIT** [comment]
Hi @choran 

I have asked CS about the unsubscribe feature scope.

Thank you for checking this out in the API!

Thomas.

**Comment by choran** [comment]
Hi @P9GIT 
I just wanted to update you on this issue. I spoke with CS about it also and they confirmed it is something we are aware of and are looking into to see how best to approach this.
So for now it is not an issue with the SDK as such, i.e. there is nothing in the SDK that we can change to address this so I will close this issue here.
CS will follow up with your directly on any updates relating to your specific request.
Thanks
Cathal
