### ISSUE TITLE
Getting NameError (uninitialized constant Intercom)

### ISSUE THREAD

**Issue by hadiS** [intercom/intercom-ruby#351]
## Version info
  - intercom-ruby version: 3.5.10
  - Ruby version: 2.2.0
  - Rails version: 4.2.0

I call in my Rails Model (User): intercom = Intercom::Client.new(token: ENV["INTERCOM"])

In development environment on my local machine it works perfectly, but in  production env on the production server I get the following Exception: 

NameError (uninitialized constant Intercom)

**Comment by choran** [comment]
Hi @hadiS 
It is probably better if you open this issue in the [Rail repo](https://github.com/intercom/intercom-rails). They would have more context there for this issue
Thanks
Cathal
