### ISSUE TITLE
Issues with response parsing

### ISSUE THREAD

**Issue by yozzz** [intercom/intercom-ruby#358]
## Version info
  - intercom-ruby version: `3.5.20`
  - Ruby version: 2.4

## Expected behavior
`intercom.users.all.first`
Get first user 

## Actual behavior
will return .`/gems/intercom-3.5.20/lib/intercom/request.rb:103:in `parse_body`
This error also return on other API calls
https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/request.rb#L103

I was trying to figure-out why i'm getting empty `@rate_limit_details`, on version `3.5.12`. So I have tried to update to the latest version, seems like it's very fresh :)

**Comment by P9GIT** [comment]
What does that '&' do in this line: https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/request.rb#L103

This update breaks the gem for us: Fired exception(class: NoMethodError, message: undefined method `&' for #<Hash:0x000000065a5798>

We use ruby 2.2.5 and Rails 5.1.
