### ISSUE TITLE
Update to latest version 3.5.20 gives error. ActionView::Template::Error (undefined method `&' for #<Hash:0x000000000308d218>)

### ISSUE THREAD

**Issue by affan00** [intercom/intercom-ruby#361]
## Version info
  - intercom-ruby version: 3.5.20
  - Ruby version: 2.3.2

I am using intercom gem on my project and today I have update intercom version from 3.5.19 to 3.5.20 but after update, it's not working fine. It gives an error mentioned below in the screenshot. 

## Logs

![image](https://user-images.githubusercontent.com/14149453/31605125-df690b78-b27e-11e7-9ef1-ec31d122e738.png)

**Comment by choran** [comment]
Hi @affan00 
We are investigating an issue with different ruby versions which seems related to #353 
There is a new PR submitted to address this and we are currently reviewing it and will update and release this today to resolve this issue. I think that should address this issue
Thanks for the update
Cathal

**Comment by affan00** [comment]
thanks for the update, @choran,

**Comment by choran** [comment]
Hi @affan00 
A new version has been released now.
I think this should address the issue you are seeing here.
It removes the lonely operator change.
I will close this for now but please  reopen and let me know if you are still seeing any issues.
I can then look into that separately.
Thanks
Cathal

**Comment by affan00** [comment]
@choran the issue is fixed now, Everything seems to be working fine, thanks.
