### ISSUE TITLE
unexpected error w/ segments method

### ISSUE THREAD

**Issue by mattsly** [intercom/intercom-ruby#364]
Querying a segment by an existing segment ID is throwing an unexpected error.

## Version info
  - intercom-ruby version:  3.5.21
  - Ruby version: ruby 2.3.1p112

## Expected behavior
Looking at the docs here (https://github.com/intercom/intercom-ruby#segments) I would expect the segment object to be returned

## Actual behavior
`Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Not authorized to access resource and http_code: '401'. Please contact Intercom with these details.`

## Steps to reproduce

Hey there - I'm trying to pull information about a segment via the API, and seeing this result - the steps below include:
(Find a user and assign to variable user)
```
[25] pry(main)> user.id
=> "56162b623c727124e30002fe"
[26] pry(main)> user.segments.first.id
=> "59809c2c2425cba042544d95"
[27] pry(main)> intercom.segments.find(id: "59809c2c2425cba042544d95")
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Not authorized to access resource and http_code: '401'. Please contact Intercom with these details.

```

**Comment by mattsly** [comment]
Note that after being approved by Intercom for extended access for my app token, I am no longer seeing this / so it appears to be permission related / but I didn't see anything in the docs I was looking at the segment reading is restricted based on extended access

**Comment by choran** [comment]
Hi @mattsly 
Thanks for the update. Glad to hear you got it working. I agree the error code could be a little bit more explicit. As a workaround I have added a [warning note](https://developers.intercom.com/docs/personal-access-tokens#section-standard-scopes) in the access token section of the docs to note that if you see a 401 it may indicate you need to apply for extended scopes. 
Hopefully this will help identify the issue a little more clearly. Thanks for noting this.
Cathal
