### ISSUE TITLE
Is it possible to use after param in the conversations query?

### ISSUE THREAD

**Issue by ksevelyar** [intercom/intercom-ruby#377]
Hello! I have a question, not an issue, may I hope you answer it?

The doc says it is possible to limit query by using the `before` param:
```
intercom.conversations.find_all(type: 'admin', id: 7, open: false, before: 1374844930).each {|convo| ... }
```

Is it possible to use something like `after` param? The `after` param does nothing in `3.5.23`.

If it is not possible — is there any other way to fetch the conversations for only last week?

It is really slow to fetch all conversations and filter them with ruby `.select`.

**Comment by theandrewykim** [comment]
Hi @ksevelyar ! 

It's not currently possible to list conversations that were updated after a specific timestamp with the REST API - you'd have to `sort_by` `updated_at` and `order` by `desc`. This might be faster than using the `select` enumerator, if you iterate through the conversation object we return yourself.

Definitely happy to let the team know that this is something you'd like to be able to do through the REST API!
