### ISSUE TITLE
handle rate limit issue - negative time interval

### ISSUE THREAD

**Issue by choran** [intercom/intercom-ruby#385]
#### Description

Issue was noted where the following error was raised `ArgumentError: time interval must be positive`  whenever they list conversations using the ruby sdk (latest release).
The customer is initializing the client as follow:
```
Intercom::Client.new(

app_id: our_api_key,

token: our_token,

handle_rate_limit: true

) 
```
Then they are calling the following function:
```
def records

client.conversations.find_all({:id => ""}).each do |record|

yield JSON.parse(record.to_json())

end

end
```
It was mentioned that the job fails in the following line:
https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/request.rb#L77
It seems to be due to the rate limit handling as the error is occuring when  "sleep (@rate_limit_details[:reset_at] - Time.now.utc).ceil" is called.
Sleep (var) with a negative var causes this error.

**Comment by choran** [comment]
Opening this in Ruby SDK in case other customers have seen similar issues. Need to check when this occurs when listing conversations. I would have through the reset time would always be ahead of now time.

**Comment by theandrewykim** [comment]
The test case we in our current specs looking for is flawed and isn't catching the broken logic in the actual method where we're creating rate limit details. We were converting the time returned in the response headers to an integer `2018` which was read as 0000002018. The aboveaddresses that, and also ensures that we won't call sleep if the the current time is outdated in the case of slow processing.

**Comment by theandrewykim** [comment]
Closing this one out for now!
