### ISSUE TITLE
How can i move to access token from API key ?

### ISSUE THREAD

**Issue by kurianic** [intercom/intercom-ruby#388]
I am a newcomer to Ruby On Rails and I need to change the intercom API key to access token method can anyone help me? I am using Intercom-rails and intercom (v2.1.1 ). Thanks in advance.

**Comment by theandrewykim** [comment]
Hey @kurianic - you should only have to migrate to a personal access token for the Intercom specific gem, not the intercom-rails gem.

Is there a reason you're not using a newer version of the gem? Our latest version is at 3.5.23: https://github.com/intercom/intercom-ruby/releases

Switching over to Personal Access Tokens on this version should be easy. Wherever you're initializing your Intercom client - you would just a personal access token like so:
```
intercom = Intercom::Client.new(token: 'my_token')
```

Don't forget to apply for extended scopes if you haven't already, and are making calls that requires those permissions! https://developers.intercom.com/docs/personal-access-tokens

**Comment by kurianic** [comment]
@theandrewykim  thank you its working fine.

**Comment by theandrewykim** [comment]
Great! Let us know if you run into any issues.
