### ISSUE TITLE
How to create visitors?

### ISSUE THREAD

**Issue by 8vius** [intercom/intercom-ruby#391]
## Version info
  - intercom-ruby version: 3.5.17
  - Ruby version: 2.4.0

`Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Visitor id or user_id must be supplied and http_code: '400'. Please contact Intercom with these details.`

Trying to create a visitor the same way I create a user always yields this error. Can't seem to find anything in the docs that can help.

**Comment by theandrewykim** [comment]
@8vius Hey there! If you're looking to

**Comment by 8vius** [comment]
@theandrewykim leads might work, the thing is visitors I thought would be more appropriate since what I want to do is tracking on donors on my site, and donors aren't really users that are later gonna join and use the service. Am I confused here?

**Comment by theandrewykim** [comment]
@8vius  I hear you! So at the moment, Leads and Users are the only two types of people that show up on your platform.

In Intercom terms, a visitor is simply anyone who visits your site and doesn't perform any actions that will identify them. So in this case, it seems like a Lead would be best suited to what you're looking for, as a person who isn't signed up, but you'd still like to be able to reach out to and contact. Does that make sense?

**Comment by 8vius** [comment]
Yep, seems that's what I need then, thanks @theandrewykim!

**Comment by theandrewykim** [comment]
Anytime! Feel free to write into Intercom if you need anything else :)
