### ISSUE TITLE
X-RateLimit-Reset doesn't parse correctly

### ISSUE THREAD

**Issue by kirbydcool** [intercom/intercom-ruby#398]
Looks like the `X-RateLimit-Reset` header is sent as a UTC epoch timestamp, which `Time.parse` won't be able to parse. This raises an `ArgumentError: argument out of range`
See https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/request.rb#L113

## Version info
  - intercom-ruby version: 3.5.24
  - Ruby version: 2.5.0

## Expected behavior
intercom-ruby should parse rate limiting headers

## Actual behavior
It throws an error

## Steps to reproduce
 1. Make some http requests (e.g. `intercom.users.find ...`) until you get the rate limit headers on the response
 2. `ArgumentError: argument out of range` is raised.

## Logs
```
[28] pry(main)> user = intercom.users.find(user_id: "1")
ArgumentError: argument out of range
```

**Comment by jonnyom** [comment]
Merged the fix above. Closing this out. Feel free to reopen if you start seeing this again.
