### ISSUE TITLE
ArgumentError: argument out of range

### ISSUE THREAD

**Issue by willrodriguez** [intercom/intercom-ruby#401]
While upgrading to Rails 4.2.10 and Ruby 2.4.4 I am now unable to retrieve intercom users. I have tried several email address that were previously working.

## Version info
  - intercom-ruby version: 3.5.24
  - Ruby version: 2.4.4

## Expected behavior
I expect to retrieve the intercom user associated with the email address.

## Actual behavior
```
ArgumentError: argument out of range
from /Users/Will/.rbenv/versions/2.4.4/lib/ruby/2.4.0/time.rb:306:in `local'
```

## Steps to reproduce
Run the following in a rails console
```
RlIntercom.users.find(email: 'ANYEMAIL')
```

## Logs
```
…/appuser/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/
time.rb: 306:in `local'
…/appuser/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/
time.rb: 306:in `make_time'
…/appuser/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/
time.rb: 370:in `parse'
…uby/2.4.0/gems/intercom-3.5.24/lib/intercom/
request.rb: 113:in `set_rate_limit_details'
…uby/2.4.0/gems/intercom-3.5.24/lib/intercom/
request.rb:  70:in `block in execute'
```

**Comment by bcackerman** [comment]
@theandrewykim Confirmed `3.5.25` fixed this
