### ISSUE TITLE
We should clarify in the readme how to use the update contact endpoint

### ISSUE THREAD

**Issue by kmossco** [intercom/intercom-ruby#404]
In the `/users` endpoint we are using the same `.create` method both for [creating and updating the user](https://developers.intercom.com/v2.0/reference#create-or-update-user). However, for the `/contacts` endpoint they are two different endpoints:

https://developers.intercom.com/v2.0/reference#create-lead only needs to be passed an email to create a contact

```curl
curl https://api.intercom.io/contacts \
-X POST \
-H 'Authorization:Bearer <Your access token>' \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' -d '
{
  "phone": "123987456",
  "email": "winstonsmith@truth.org",
  "name": "Winston Smith"
}'
```
 
https://developers.intercom.com/v2.0/reference#update-lead requires that we send the request with at least **user_id** or **intercom_id**

```curl
$ curl https://api.intercom.io/contacts \
-XPOST \
-H 'Authorization:Bearer <Your access token>' \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' -d '
{
  "id": "5811f6bbe6b4704ddfa84ac0",
  "user_id": "77177570-cf5d-4f1a-bc75-75202af47d4f",
  "phone": "123987456",
  "email": "obrien@truth.org"
}'
```

So if you call `contacts.create(email: "example@example.com")` and then call it again, it will create a duplicate as it won't update the existing contact.

## Version info
  - intercom-ruby version: latest

**Comment by theandrewykim** [comment]
@kmossco Because the methods used to create/update leads and users use the same syntax in the SDK, what do you think is the best way to address this? A disclaimer beneath the contacts endpoint with a link to our docs?

**Comment by kmossco** [comment]
@theandrewykim I think that having an example of each would be sufficient. Here's how I've done it in the dotnet repo: 

![image](https://user-images.githubusercontent.com/11810153/41584368-07921fe0-739f-11e8-8026-78efdd711126.png)

So this way you know there are multiple ways to do this, and we can also add a link to the docs for good measure. 👍

**Comment by choran** [comment]
cool, makes sense.
I added a callout and example in the contacts section to better clarify this
Let me know if you think it needs more clarification
