### ISSUE TITLE
Conversations get All endpoint (without admin_id or user email).

### ISSUE THREAD

**Issue by wyattbenno777** [intercom/intercom-ruby#407]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-ruby version: N/A
  - Ruby version: N/A

## Expected behavior

I see an endpoint to get all conversations. https://developers.intercom.com/reference#list-conversations
Without using admin_id or user email. 

The this gem does not have documentation on this and it looks like it does not exist in the gem.

We can do HTTP methods directly on the Intercom object e.g.
intercom.get("/conversations", "")

**Comment by choran** [comment]
HI @wyattbenno777 
Yes, this is a good catch and something I have been meaning to raise as well. We do not provide the default behaviour where you can list all your conversations in this SDK. I noticed this as well when writing this [blog post](https://developerblog.intercom.com/a-beginners-guide-to-exporting-intercom-conversations-with-the-conversations-api-d7bb1c24983c) and used the same workaround you noted here to list all conversations i.e. `intercom.get("/conversations", "")`.

So I do think we need to add this to the SDK. It has already been tagged as a feature request and we will put it in the queue of work needed for the ruby SDK. 
In the meantime feel free to submit any PR if you want and we can review that.
thanks again
