### ISSUE TITLE
Can't convert lead after finding

### ISSUE THREAD

**Issue by andrewhavens** [intercom/intercom-ruby#419]
## Version info
  - intercom-ruby version: 3.5.25
  - Ruby version: 2.5.1

## Expected behavior
I should be able to find a lead by email and convert it to a user.

## Actual behavior
Can't convert lead after finding due to "user_id not set" error.

## Steps to reproduce
```ruby
lead = INTERCOM.contacts.find(email: email)
puts "found lead: #{lead.inspect}"
result = INTERCOM.contacts.convert(lead, Intercom::User.new(email: email))
```
Raises an exception:
> Intercom::AttributeNotSetError: 'user_id' called on Intercom::Contact but it has not been set an attribute or does not exist as a method

## Logs
```
found lead: #<Intercom::Contact:0x00007fd66ec08ec8 @changed_fields=#<Set: {}>, @custom_attributes={}, @type="contact.list", @pages=#<Intercom::Pages:0x00007fd66fc0b820 @changed_fields=#<Set: {}>, @type="pages", @next=nil, @page=1, @per_page=50, @total_pages=1>, @contacts=[{"type"=>"contact", "id"=>"59bc95152e808aa94484cfc2", "user_id"=>"e8bebb12-2995-4c0d-b2ca-5a436f101b31", ...
```

**Comment by andrewhavens** [comment]
Hmm...I think the problem might be with `find`. Instead, I used `findAll` and it seemed to work.

```ruby
lead = INTERCOM.contacts.findAll(email: email).to_a.first
puts "found lead: #{lead.inspect}"
result = INTERCOM.contacts.convert(lead, Intercom::User.new(email: email))
# => #<Intercom::User:0x00007fc143e74a58
# ...
```

**Comment by jonnyom** [comment]
So the reason that this is happening is actually because `find` returns a list of objects when the only parameter that is supplied is `email`. This is because there can be duplicate users with that email address.

That list is returned as a `Contact` object with type `contact.list`.

```ruby
[4] Intercom(GEM)> email = "tester@testing.com"
[36] Intercom(GEM)> client.contacts.find(email: email)
=> #<Intercom::Contact:0x00007ff3a80789f8
 @changed_fields=#<Set: {}>,
 @contacts=
  [{"type"=>"contact",
    "id"=>"5b7fd9b683681ac52274b9c7",
    "user_id"=>"05bc4d17-72cc-433e-88ae-0bf88db5d0e6",
    "anonymous"=>true,
    "email"=>"tester@testing.com",
    ...},
   {"type"=>"contact",
    "id"=>"5b7fd8ba83681ac52274b9c6",
    "user_id"=>"9aee3dcd-929b-46fe-ae7e-a076298d0a90",
    "anonymous"=>true,
    "email"=>"tester@testing.com",
    ...],
 @custom_attributes={},
 @limited=false,
 @pages=#<Intercom::Pages:0x00007ff3a7413c58 @changed_fields=#<Set: {}>, @next=nil, @page=1, @per_page=50, @total_pages=1, @type="pages">,
 @total_count=2,
 @type="contact.list">
[37] Intercom(GEM)> lead = client.contacts.find(email: email).contacts.first
=> {"type"=>"contact",
 "id"=>"5b7fd9b683681ac52274b9c7",
 "user_id"=>"05bc4d17-72cc-433e-88ae-0bf88db5d0e6",
 "anonymous"=>true,
 "email"=>"tester@testing.com",
 ...
[38] Intercom(GEM)>
```

If you apply that lead object that returns multiple users because we don't know which user you're looking for. We will _always_ return a `contact.list` when you search via email.

```ruby
[5] Pry(UNK)> lead_by_email = client.contacts.find(email: email)
=> #<Intercom::Contact:0x00007fd54d3aca08
 @changed_fields=#<Set: {}>,
 @contacts=
  [{"type"=>"contact",
    "id"=>"5b800ca2dfc90e434615404c",
    "user_id"=>"523c4552-b59d-4089-80db-4afb69386ce0",
    "anonymous"=>true,
    "email"=>"tester_email@testingme.com",
    ...
   }],
 @custom_attributes={},
 @limited=false,
 @pages=#<Intercom::Pages:0x00007fd54d3a5528 @changed_fields=#<Set: {}>, @next=nil, @page=1, @per_page=50, @total_pages=1, @type="pages">,
 @total_count=1,
 @type="contact.list">
```

You can access that lead's information by calling `contacts.first` which will return contact as a hash.
```ruby
[9] Pry(UNK)> lead.contacts.first
=> {"type"=>"contact",
 "id"=>"5b800ca2dfc90e434615404c",
 "user_id"=>"523c4552-b59d-4089-80db-4afb69386ce0",
 "anonymous"=>true,
 "email"=>"tester_email@testingme.com",
 ...}
```

If you use the lead's Intercom ID (which gets returned when you create the lead, which you should store in your local data store) you will get the correct `Contact` object.
```ruby
[13] Pry(UNK)> lead_by_id = client.contacts.find(id: "5b800ca2dfc90e434615404c")
=> #<Intercom::Contact:0x00007fd54d3775d8
 @anonymous=true,
 @app_id="xxxxxx",
 @avatar=#<Intercom::Avatar:0x00007fd54d366990 @changed_fields=#<Set: {}>, @image_url=nil, @type="avatar">,
 @changed_fields=#<Set: {}>,
 @companies=[],
 @created_at=1535118498,
 @custom_attributes={},
 @email="tester_email@testingme.com",
 @id="5b800ca2dfc90e434615404c",
 @type="contact"
 ...>
```

You can then use this object correctly to convert the lead to a user
```ruby
[15] Pry(UNK)> user = client.contacts.convert(lead_by_id, client.users.create(email: lead_by_id.email))
=> #<Intercom::User:0x00007fd54d48d9b8
 @anonymous=false,
 @app_id="zvpy2vce",
 @avatar=#<Intercom::Avatar:0x00007fd54cd2cb38 @changed_fields=#<Set: {}>, @image_url=nil, @type="avatar">,
 @changed_fields=#<Set: {}>,
 @companies=[],
 @created_at=1535121296,
 @custom_attributes={},
 @email="tester_email@testingme.com",
 @has_hard_bounced=false,
 @id="5b801790ae06f88905453ebc",
 @type="user"
 ...>
```

This is why when you call `find_all`, we return a list of Contacts, so when you convert it to an array and call the first object, that actually returns a Contact object that you can pass into the `convert` call.

This maintains the RESTful nature of our API, as you aren't providing an ID attribute when `find`ing by email, so we need to return a list of objects.

I hope that clarifies things!

Going to close out as this isn't actually an issue, but will work on getting the docs updated to reflect this. 👍

**Comment by andrewhavens** [comment]
@jonnyom Thanks for the explanation! Makes sense now.

**Comment by jonnyom** [comment]
@andrewhavens Glad that makes sense. I can understand your thinking there. We may look into implementing `find` to only return one record in a future iteration. Thanks for raising this! Very interesting stuff 😄

**Comment by sowenjub** [comment]
Hey @jonnyom I still stumbled on that issue but it seems things have changed.

When doing

```
contact = intercom.contacts.find(email: "email@example.com")
user = intercom.users.find(user_id: 1)
intercom.contacts.convert(contact, user)
```

I get

> Intercom::UnexpectedError (The error of type '' is not recognized. It occurred with the message: Contact id or user_id must be supplied and http_code: '400'. Please contact Intercom with these details.)

Even though the contact here is a proper Intercom::Contact object.
Have I missed something?

**Comment by jonnyom** [comment]
Hey @sowenjub that's definitely strange. It should work. Could you message into our support team via the Messenger on https://developers.intercom.com ? They'll be able to help out and pull up some logs for you that will help to narrow that down. If you want to post back here with what you guys find then feel free 😄

**Comment by sowenjub** [comment]
Thanks @jonnyom, I just contacted your support team.
