### ISSUE TITLE
Can't access event list when doing intercom.events.find_all for a user

### ISSUE THREAD

**Issue by kmossco** [intercom/intercom-ruby#436]
## Version info
  - intercom-ruby version: `intercom-3.6.2`
  - Ruby version: `ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]`

## Expected behavior
Should be able to iterate on the event list that is returned when running this line of code:

```ruby
intercom.events.find_all("type" => "user", "intercom_user_id" => "59ec790de50d01ddf9e1c1dc")
```
## Actual behavior
I tried multiple ways to get this list, but I keep bumping into this error:

```
NoMethodError: undefined method `each' for nil:NilClass
from /home/kmossco/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/intercom-3.6.2/lib/intercom/client_collection_proxy.rb:52:in `deserialize_response_hash'
```

[Affected line of code](https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/client_collection_proxy.rb#L52).

## Steps to reproduce
My code is:

```ruby
require "intercom"
require "pp"
require "pry"

intercom = Intercom::Client.new(token: 'token=')

users = []

pp events = intercom.events.find_all("type" => "user", "intercom_user_id" => "59ec790de50d01ddf9e1c1dc")
binding.pry
```

I get this in the events variable:

```ruby
#<Intercom::EventCollectionProxy:0x000055836275ef00
 @client=
  #<Intercom::Client:0x000055836275c4a8
   @base_url="https://api.intercom.io",
   @handle_rate_limit=false,
   @password_part="",
   @rate_limit_details={:limit=>83, :remaining=>83, :reset_at=>2018-10-11 16:29:30 +0100},
   @timeouts={:open_timeout=>30, :read_timeout=>90},
   @username_part="token">,
 @finder_params={"type"=>"user", "intercom_user_id"=>"59ec790de50d01ddf9e1c1dc", "summary"=>"true"},
 @finder_url="/events",
 @resource_class=Intercom::Event,
 @resource_name="events">
```

And I tried:

```ruby
events.to_a
events.first
events.entries
events.each { |ev| ev.inspect }
```

Looking at the available methods, I can see that `events` responds to `entries`, `to_a`, `to_h` and others.

**Comment by choran** [comment]
Hi @kmossco 
Maybe I am misunderstanding you  but I think this is possible, i.e. to list the events. For example I tried this.
```
events = intercom.events.find_all("type" => "user", "intercom_user_id" => "584b63a6dbc")
```
Like you said then getting the first entry should work:
```
events.first
=> #<Intercom::Event:0x00007fd6e05daf70
 @changed_fields=#<Set: {}>,
 @created_at=1541423392,
 @email="sartre@existentialist.com",
 @event_name="invited-friend",
 @id="14d010d4-efc-118-a04b-22842",
 @intercom_user_id="123",
 @metadata={"invitee_email"=>"pi@example.org", 
"invite_code"=>"ADDAFRIEND", 
"found_date"=>1290936440},
 @type="event",
 @user_id="1940">
```
And you should be able to list the names of the events for example via
```
events.each {|ev| puts ev.event_name}
invited-friend
invited-friend
invited-friend
invited-friend
```
That all appears to work but maybe there was some thing specific that you were trying to do that i missed? If there is please feel free to re-open this. But I think you should be able to list over the events, I am just not sure why it wasnt working for you earlier
