### ISSUE TITLE
intercom.users.scroll.next method always return the same scroll_param

### ISSUE THREAD

**Issue by BastienL** [intercom/intercom-ruby#452]
When trying to embed the `scroll.next` method inside our app, we discovered that the same `scroll_param` was returned on every subsequent calls.

## Version info
  - intercom-ruby version: 3.7.1
  - Ruby version: 2.5.3

## Expected behavior

Every new call to `intercom.users.scroll.next` with the `scroll_param` from the previous call to `intercom.users.scroll.next` should return a new `scroll_param` to jump to the next 100 users. 

## Actual behavior

```
> result = intercom.users.scroll.next
> result.scroll_param
=> "60bb598b-0fb9-4f98-9aa8-4f23bca2cda1"
> result = intercom.users.scroll.next("60bb598b-0fb9-4f98-9aa8-4f23bca2cda1")
> result.scroll_param
=> "60bb598b-0fb9-4f98-9aa8-4f23bca2cda1"
```

So there's no way we can get to the next 100 users.

## Steps to reproduce
 1. Create an `Intercom::Client`
 2. Execute `result = intercom.users.scroll.next`
 3. Execute `result = intercom.users.scroll.next(result.scroll_param)`
 4. Notice that you'll loop indefinitely.

**Comment by theandrewykim** [comment]
Hi @BastienL - it is true that the scroll param returned for each scroll is the same as you paginate through requests - but you should be able to continue to paginate through the scroll even with the same scroll param.

Are you seeing any errors returned when you input the same scroll_param with:
`result = intercom.users.scroll.next(result.scroll_param)` ? 
If you enter
`result.records.first.email` - is that email the same user as the first user returned in the original scroll call?

**Comment by BastienL** [comment]
Hi @theandrewykim, you're right, I was expecting to get a different value for the `scroll_param` and forgot to check the records themselves. My bad, we're indeed looping through the results even though the value of `scroll_param` doesn't change from one call to another 👍

**Comment by theandrewykim** [comment]
@BastienL No problem! Glad things are working!
