### ISSUE TITLE
Search user by phone (other param)

### ISSUE THREAD

**Issue by guy-bensh** [intercom/intercom-ruby#460]
Currently the API has only "find" user by: id, email, user_id `intercom.users.find`
or "find_all" with no filter (only with "created_since" filter param) `intercom.users.find_all(type: 'users', ...)`

I'm trying to search user by phone, therefore, my "solution" is to use the scroll functionality and "filter" the records in my code. **Performance wise is very bad!**

Is there a better solution that you recommend? I think you should add the option to search by other params - Index other params in your elasticsearch.

Thanks!

**Comment by theandrewykim** [comment]
Hi @guy-bensh Thanks for the feedback! We don't currently have a way to list or index for users by other parameters at the moment. What you're doing right now is the right way to do things.

This isn't a function of the ruby wrapper, more so a functionality of the actual API. Your feedback and any questions you have about overall API functionality, are best served by writing into our messenger at Intercom, or emailing team@intercom.com. Our Support Engineering team is happy to help you out there as well as field any feedback.
