### ISSUE TITLE
Error while saving user after upgrading to API 1.1: User email, user_id or anonymous_id must be supplied

### ISSUE THREAD

**Issue by andrewhavens** [intercom/intercom-ruby#471]
## Version info
  - intercom-ruby version: 3.7.6
  - Ruby version: 2.5.5
  - Intercom API version: 1.1

## Expected behavior
Saving user is successful. (This works when using API 1.0)

## Actual behavior
Error:
> Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: User email, user_id or anonymous_id must be supplied and http_code: '400'. Please contact Intercom with these details.

## Steps to reproduce
```ruby
user = begin
  $intercom.users.find(email: email)
rescue Intercom::ResourceNotFound
  $intercom.users.create(email: email, name: full_name)
end
user.custom_attributes["Order ID"] = order.id
$intercom.users.save(user)
```

## Logs
```
…ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/request.rb: 197:in `raise_application_errors_on_failure'
…ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/request.rb: 114:in `parse_body'
…ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/request.rb:  77:in `block in execute'
      /app/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/http.rb: 910:in `start'
…ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/request.rb:  72:in `execute'
…/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/client.rb: 136:in `execute_request'
…/ruby/2.5.0/gems/intercom-3.7.6/lib/intercom/client.rb: 111:in `post'
…ems/intercom-3.7.6/lib/intercom/api_operations/save.rb:  27:in `save'
```

**Comment by theandrewykim** [comment]
Hey @andrewhavens I've had no luck reproducing this on my end. Are you still having trouble with v1.1 of our API?

**Comment by adambedford** [comment]
I'm having this issue as well. Any resolution?
