### ISSUE TITLE
scroll already exists for this app

### ISSUE THREAD

**Issue by evyasafhouzz** [intercom/intercom-ruby#474]
Hi,
I'm trying to "Scroll over all users" from the Intercom API but I keep getting the  error :
{'code': 'scroll_exists', 'message': 'scroll already exists for this app'}

I'm getting the error message no matter how much time I'm waiting (more than one minute).

Notes:
- I'm not sending the 'scroll_param' on the request

What can I do to reset the scroll?

Looking forward for any response

**Comment by theandrewykim** [comment]
Hey @evyasafhouzz - it looks like you might be better served reaching out to our Support team via team@intercom.io, or writing into our messenger on Intercom. Our support team can dig up some logs and figure out what's going on!
