### ISSUE TITLE
Intercom::RateLimitExceeded (Exceeded rate limit of 83 in 10_seconds)

### ISSUE THREAD

**Issue by a-kulbei** [intercom/intercom-ruby#475]
It looks like Intercom updated rate api limits, limiting 83 request per 10 sec. When I try to fetch list of conversations with intercom ruby client - i am getting API Limit exception. On the other hand - I do not see a way to paginate in documentation. What would be the correct way of fixing that?

## Version info
  - intercom-ruby version: 3.7.5
  - Ruby version: 2.5.3

## Expected behavior
Intercom API Client should handle updated rate limits correctly

## Actual behavior
Intercom::RateLimitExceeded (Exceeded rate limit of 83 in 10_seconds)

## Steps to reproduce
`api = Intercom::Client.new(token: <token>)
  api.conversations.all.count
`
## Logs
Intercom::RateLimitExceeded (Exceeded rate limit of 83 in 10_seconds)
api.rate_limit_details
{:limit=>83, :remaining=>0, :reset_at=>2019-06-07 14:06:40 +0000}

**Comment by leadstar116** [comment]
@a-kulbei How did you solve this?
