### ISSUE TITLE
Intercom::ResourceNotFound on user create

### ISSUE THREAD

**Issue by vitalinfo** [intercom/intercom-ruby#481]
## Version info
  - intercom-ruby version: 3.8.0
  - Ruby version: 2.6.4

## Expected behavior
`Intercom::Client.new(token: ENV['INTERCOM_TOKEN'], handle_rate_limit: true).users.create(email: EMAIL)` doesn't raise `ResourceNotFound`

## Actual behavior
When I try to create user get `Intercom::ResourceNotFound`

## Steps to reproduce
 I don't have strong reproduce, because it happened not for all users, but very-very often.

## Logs
```
/gems/intercom-3.8.0/lib/intercom/request.rb:175 in raise_application_errors_on_failure
/gems/intercom-3.8.0/lib/intercom/request.rb:114 in parse_body
/gems/intercom-3.8.0/lib/intercom/request.rb:77 in block in execute
vendor/ruby-2.6.4/lib/ruby/2.6.0/net/http.rb:920 in start
918:
        begin
919:
          do_start
920:
          return yield(self)
921:
        ensure
922:
          do_finish
/gems/intercom-3.8.0/lib/intercom/request.rb:72 in execute
/gems/intercom-3.8.0/lib/intercom/client.rb:140 in execute_request
/gems/intercom-3.8.0/lib/intercom/client.rb:115 in post
/gems/intercom-3.8.0/lib/intercom/api_operations/save.rb:27 in save
/gems/intercom-3.8.0/lib/intercom/api_operations/save.rb:19 in create
```

**Comment by CapsuleMaglev** [comment]
Bump!
I am having exactly the same issue. Happens for about 10% of our users and creates a lot of noise in error reporting.

**Comment by docstun** [comment]
Bump!

Same here. Any way around this?

**Comment by adsteel** [comment]
I don't think this is a gem issue, I think it's an API issue.

We've built a retry mechanism into all of our calls because of the regular, brief service outages of the Intercom API. So we retry on this error as well for the `users.create` call and the problem has disappeared.

**Comment by Javierchik** [comment]
Bump!

Same here. I'll create a retry mechanism.

**Comment by adsteel** [comment]
If it helps anyone, there's a long list of errors we've compiled that seem to arise from brief service outages on Intercom's part. Not sure why they aren't all 500s, but maybe has to do with internal services failing?

Anyway, just added another yesterday, but here's our current list:

```ruby
  INTERCOM_OUTAGE_ERRORS = [
    Intercom::ServerError,
    Intercom::UnexpectedError,
    Intercom::ServiceUnavailableError,
    Intercom::BadGatewayError,
    Intercom::ServiceConnectionError,
    Intercom::GatewayTimeoutError,
    EOFError,
    Intercom::AuthenticationError,
    OpenSSL::SSL::SSLError
  ].freeze
```

**Comment by JakubKopys** [comment]
Any updates on this? Still running into this bug

**Comment by theandrewykim** [comment]
@adsteel is right, this would have been an API issues versus gem issue. https://github.com/intercom/intercom-ruby/issues/481#issuecomment-575446994 

This should have gotten better over the years, but feel free to write in at intercom.com if you're still running into issues!
