### ISSUE TITLE
run_assignment_rules is not available :(

### ISSUE THREAD

**Issue by deneuxa** [intercom/intercom-ruby#482]
curl 'https://api.intercom.io/conversations/{convo_id}/run_assignment_rules'
-X POST 
-H 'Authorization: Bearer <Acess Token>=' 
-H 'Accept: application/json' 
-H 'Content-Type: application/json'

=> This method is not available con the ruby gem. It would be super cool to implement. Thanks

**Comment by jonnyom** [comment]
Hey @deneuxa that definitely would be cool! We accept PRs so if you fancy taking a stab at it you're more than welcome

**Comment by deneuxa** [comment]
Done.

We can pay you guys (a lot !) and code for you, but then you have to be nice with us :p

**Comment by murtron** [comment]
We've added support for this feature in 4.0.0 🙂
