### ISSUE TITLE
Intercom::UnexpectedError: The error of type '' is not recognized. It occurred with the message: Company Not Found and http_code: '404'. 

### ISSUE THREAD

**Issue by nmdoliveira** [intercom/intercom-ruby#484]
## Version info
  - intercom-ruby version: 3.8.0
  - Ruby version: 2.5.1

## Expected behavior

`Intercom::ResourceNotFound` is raised when trying to tag a company that does not exist

## Actual behavior

`Intercom::UnexpectedError` was raised instead, with this message: 

```
The error of type '' is not recognized. It occurred with the message: Company Not Found and http_code: '404'. 
```

## Steps to reproduce
 1. Try to tag a company that does not exist:
```
client = Intercom::Client.new(token: your_token)
client.tags.tag(
  name: "your_tag",
  companies: [{ company_id: id_that_does_not_exist }]
)
```

## Logs

This was the response body returned by the API:

```
{
  "type":"error.list",
  "request_id":"<request_id>",
  "errors":[
    {
      "code":"company_not_found",
      "message":"Company Not Found"
    }
  ]
}
```

---

I think that the `company_not_found` code could be added to this line: https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/request.rb#L174.
I can send a PR if that's ok.

**Comment by bart3r** [comment]
I am experiencing this same issue.
Is anyone looking into this?

**Comment by vdbilt** [comment]
Same issue here!
`
Intercom::UnexpectedError (The error of type '' is not recognized. It occurred with the message: Company Not Found and http_code: '404'. Please contact Intercom with these details.)
`

**Comment by jonnyom** [comment]
Hey folks! This could definitely be handled by the SDK.

Please feel free to submit a PR 😄

**Comment by jonnyom** [comment]
3.8.1 has now been released that bundles this change 😄
