### ISSUE TITLE
Bug: Intercom is running on the wrong timezone in Brazil

### ISSUE THREAD

**Issue by giovannibonetti** [intercom/intercom-ruby#495]
In 2019 the [Brazilian government has ended Daylight Savings Time in Brazil](https://www.business-standard.com/article/news-ians/bolsonaro-ends-daylight-savings-time-in-brazil-119042600163_1.html). However Intercom is not aware of that, and my company - as a long time user of Intercom - is having issues to work with the app today since the clock is wrong. It bothers us very much since we use the snooze functionality very often, and that is very dependent on the current time.

The timezone here in São Paulo is UTC-03 but Intercom still thinks its DST now and so it shows the time as UTC-02. We tried a workaround [setting our timezone to Buenos Aires](https://www.intercom.com/help/en/articles/992690-how-do-i-change-my-app-s-local-timezone) but that doesn't solve the problem since for many features the user timezone is considered, and we don't know how to change the user's timezone since it appears to be automatically set.

Please help!

**Comment by jonnyom** [comment]
Hey @giovannibonetti this sounds like an issue with the Intercom app, not the SDK, am I right?

If so, could you please contact our support team via the Messenger in the app, or here https::developers.intercom.io/

Thanks!
