### ISSUE TITLE
private method `rate_limit_details' called for Intercom::Request

### ISSUE THREAD

**Issue by lostie** [intercom/intercom-ruby#498]
## Version info
  - intercom-ruby version: 3.9.2
  - Ruby version: 2.6.5

## Expected behavior

Perform an API request to create a user should execute with no expected errors

## Actual behavior

An error occurs due to the changes in the most recent gem version bump where the method called here https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/client.rb#L146 got privatised.

## Steps to reproduce
 1. Use the API client to perform a request to create a user

## Logs

```ruby
     Failure/Error: api_client.users.create(user_attributes)

     NoMethodError:
       private method `rate_limit_details' called for #<Intercom::Request:0x00007fdec4f829d8>
       Did you mean?  rate_limit_details=
     .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/intercom-3.9.2/lib/intercom/client.rb:146:in `execute_request'
     .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/intercom-3.9.2/lib/intercom/client.rb:119:in `post'
     .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/intercom-3.9.2/lib/intercom/api_operations/save.rb:27:in `save'
     .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/intercom-3.9.2/lib/intercom/api_operations/save.rb:19:in `create'
```

**Comment by jonnyom** [comment]
Thanks for this @lostie it's a shame our tests didn't cover this.

Will try to get a fix out ASAP

**Comment by jonnyom** [comment]
Version 3.9.3 is now out on Rubygems. I'll do a release here shortly, Github's webhooks outage is causing a delay for builds.

**Comment by adsteel** [comment]
Hey, we just had this error, too! Thanks @jonnyom!
