### ISSUE TITLE
Handle 504 response

### ISSUE THREAD

**Issue by adsteel** [intercom/intercom-ruby#502]
Default handling for unexpected response bodies ([here](https://github.com/intercom/intercom-ruby/pull/492))
has revealed an unhandled 504 response from intercom.

Example message from UnexpectedResponseError:

```
Intercom::UnexpectedResponseError, Expected a JSON response body.
Instead got '<html> <head><title>504 Gateway Time-out</title></head>
<body bgcolor="white"> <center><h1>504 Gateway Time-out</h1></center>
</body> </html> ' with status code '504'.
```

**Comment by jonnyom** [comment]
Released in 3.9.4
