### ISSUE TITLE
Unable to use data_attributes on API V1

### ISSUE THREAD

**Issue by marinhero** [intercom/intercom-ruby#529]
## Version info
  - intercom-ruby version: 4.0.0
  - Ruby version: 2.6.5

## Expected behavior

List all data attributes using V1 API since it's included in the [Intercom V1 API docs](https://developers.intercom.com/intercom-api-reference/v1.0/reference#data-attribute-model).

```
intercom = Intercom::Client.new(token: t.token, api_version: '1.0')
attributes = intercom.data_attributes.all
attributes.each { |attribute| p attribute.name }
# printed list of attributes...
```

## Actual behavior

```
intercom = Intercom::Client.new(token: t.token, api_version: '1.0')
attributes = intercom.data_attributes.all
attributes.each { |attribute| p attribute.name }

Intercom::ApiVersionInvalid (Requested resource is not available in current API version)
```

## Steps to reproduce
1.- Create an Intercom App that uses the V1 endpoint
2.- Run the following code:
```
intercom = Intercom::Client.new(token: t.token, api_version: '1.0')
attributes = intercom.data_attributes.all
attributes.each { |attribute| p attribute.name }
```
3.- See the error. Is this expected or the support for data_attributes on V1 is broken?

## Logs

Not applicable.

**Comment by theandrewykim** [comment]
Hey @marinhero The data_attributes endpoint functions slightly different across v 1.0, and 2.0. You're best off making a raw request to the data_attributes endpoint when using older versions of the API. 

It should look something like this:

`intercom.get("data_attributes/customer",)`

Documentation here: 

https://developers.intercom.com/intercom-api-reference/v1.0/reference#data-attributes
