### ISSUE TITLE
Error with the assign function

### ISSUE THREAD

**Issue by odedharth** [intercom/intercom-ruby#539]
## Version info
  - intercom-ruby version: 4.1.1
  - Ruby version: 2.6.6

## Expected behavior

Assigning with '0' as the assignee_id moves the conversation to "unassigned".
This used to work until you made an update to Intercom yesterday. 

## Actual behavior

Now it returns an error:
`Intercom::ResourceNotFound (Resource Not Found)
`
## Steps to reproduce

Run this function with '0' as the assignee_id. 
`@intercom.conversations.assign(id: conversation_id, admin_id: admin_id, assignee_id: '0')
`

**Comment by theandrewykim** [comment]
This was an issue with our API that should have since been resolved
