### ISSUE TITLE
run_assignment_rules function returns an error

### ISSUE THREAD

**Issue by odedharth** [intercom/intercom-ruby#540]
## Version info
  - intercom-ruby version: 4.1.1
  - Ruby version: 2.6.6

## Expected behavior

The run_assignment_rules should work. 

## Actual behavior

The run_assignment_rules never works and returns the error:
`ArgumentError (wrong number of arguments (given 1, expected 2))
`
## Steps to reproduce
 Try running the function:
`@intercom.conversations.run_assignment_rules(conversation_id)
`
And see that it always returns an error.

**Comment by theandrewykim** [comment]
T
