### ISSUE TITLE
intercom.articles.all returns 25 results only with no pagination support

### ISSUE THREAD

**Issue by ro-savage** [intercom/intercom-ruby#543]
`intercom.articles.all` is only returning 25 results with no way to control pagination.

The REST API supports `per_page` and `page`

Could these params please be added, so that it's possible to get more than just the last 25 updated articles.

**Comment by JamesPaden** [comment]
I'm having the same problem.

**Comment by theandrewykim** [comment]
@ro-savage @JamesPaden The team just shipped a fix that should have dealt with this. Are things working for you now?

**Comment by JamesPaden** [comment]
+1: Thank you!

**Comment by ro-savage** [comment]
Thanks for fixing it. 

We won't be able to test it as we have already fully built our and released our feature that used articles.

We ended up using the REST API and copying all articles to our own servers nightly. As we require search functionality of the articles and intercom doesn't support this via the API.

**Comment by theandrewykim** [comment]
@ro-savage Thanks for the context! Feel free to write into team@intercom.com, or on our Messenger, and our team is happy to log the above as feature request. Will close this one for now, otherwise.
