### ISSUE TITLE
add_company' called on Intercom::Contact but it has not been set an attribute or does not exist as a method

### ISSUE THREAD

**Issue by logical-engine** [intercom/intercom-ruby#567]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-ruby version: 3.5.25
  - Ruby version: 2.6.6

## Expected behavior

Expected to be able to attach a company to an intercom contact.

## Actual behavior

Received the above error and can't attach the company to the contact. 

## Steps to reproduce
 1.  new_contact = @intercom.contacts.find(id: <contactid>) (this works fine)
 2.  company = @intercom.companies.find(company_id: <companyid>) (this works fine)
 3.  new_contact.add_company(company) (this is where I get the error)
 4. Receive Error

## Logs
      2: from /.rvm/gems/ruby-2.6.6/gems/intercom-3.5.26/lib/intercom/traits/api_resource.rb:50:in `method_missing'
        1: from /.rvm/gems/ruby-2.6.6/gems/intercom-3.5.26/lib/intercom/lib/dynamic_accessors_on_method_missing.rb:24:in `define_accessors_or_call'

**Comment by logical-engine** [comment]
Never mind - I now see the next version.

**Comment by bbugh** [comment]
If anyone else runs into this problem, the issue we had was the API token we were using was for an old API version and it was returning `Intercom::ResourceNotFound: Resource Not Found`. Creating an API token and specifying the latest version allowed `contact.add_company` to work correct.
