### ISSUE TITLE
Gateway timeout when counting conversations in test accounts only

### ISSUE THREAD

**Issue by djrodgerspryor** [intercom/intercom-ruby#568]
## Version info
  - intercom-ruby version: 2.6.3
  - Ruby version: 3.9.5

## Expected behavior

Calling `intercom_api.counts.for_type(type: 'conversation')` should return a result

## Actual behavior

What it actually does is hang and returns a socket read timeout. If I hack at the client to increase the socket read timeout, then I get a GatewayTimeout error instead.

This is an API problem, not an intercom-ruby problem (apologies, but I couldn't find where to submit API bugs, hopefully you can point me to the correct place). Here's a reproduction in curl:

```
curl https://api.intercom.io/counts?type=conversation -H 'Accept:application/json' -H 'Authorization:Bearer XXX'

<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

What's interesting is that this only happens with an app connected to a test workspace. This request works with a token from our production workspace, but not our test one. I made a whole new app connected to our test workspace, and a request with its token timed-out too.

I only have one intercom test workspace, so I can't figure out if this is a general problem with test workspaces, or just some weird state that our test workspace has.

## Steps to reproduce
 1. Using a test workspace token:
 ```
 curl https://api.intercom.io/counts?type=conversation -H 'Accept:application/json' -H 'Authorization:Bearer XXX'
 ```

**Comment by theandrewykim** [comment]
@djrodgerspryor  -- is this something you're still running into? For API-specific behaviors/bugs, I would recommend writing into our Support team, using the messenger at intercom.com. Will close this one out for now.
