### ISSUE TITLE
intercom_contact.companies is nil

### ISSUE THREAD

**Issue by kostya1241** [intercom/intercom-ruby#571]
Creating intercom contact with 'companies' collection in the user attributes hash breaks intercom_contact.companies getter.

```
> contact = intercom_client.contacts.create(email: 'randomtest1232@email.com', role: 'user', companies: [{company_id: 123, name: 'randomcompanyname'}])
> contact.companies
 => [{:company_id=>123, :name=>"randomcompanyname"}] 

# reload contact from Intercom
> contact = intercom_client.contacts.find(id: contact.id)
> contact.companies
 => nil 

```
## Version info
  - intercom-ruby version: 4.1.2
  - Ruby version: 2.7.1p83

## Expected behavior
`contact.companies` to return `ClientCollectionProxy`

## Actual behavior

`contact.companies` return `nil`

## Steps to reproduce
 1.  Run code similar to presented above

**Comment by theandrewykim** [comment]
Hey @kostya1241  -- the Contacts endpoint doesn't allow the addition of companies to it, which is why you're seeing this. You'd need to make this call:
```
# Add a contact to a company
company = intercom.companies.find(id: "123")
contact.add_company(id: company.id)
```

explicitly. I can see why this would be confusing, so will leave this one open.
