### ISSUE TITLE
Tags missing for contact

### ISSUE THREAD

**Issue by TLSDwyer** [intercom/intercom-ruby#575]
When I do a find operation on contacts (also happens when doing a search operation) I'm not getting any tags returned from the gem. I checked this in postman with a rest api call and do receive the tags back. I can also see the tags in intercom. All of the contacts are type="user", active and not archived.

## Version info
  - intercom-ruby version: 4.1.2
  - Ruby version: 2.6.7

## Expected behavior
The contact object returned from finding/searching should contain all of tags that are attached to the contact.

## Actual behavior
No tags are returned for the contact.

## Steps to reproduce
 1. I retrieve the contact by doing a find: contact = intercom.contacts.find(id: "[contactid]")
 2. I receive a normal and populated contact object
 3. The contact object is missing tags
 4. I've tried with multiple contacts without getting any tags. It does work when doing api calls via curl/postman.
 
## Logs
[57] pry(main)> contact.tags
=> nil

**Comment by theandrewykim** [comment]
@TLSDwyer  -- are you just looking at the object for the tags? Have you tried `contact.tags`? That should return a list of tag objects relevant to the contact in question.

**Comment by TLSDwyer** [comment]
I tried this again and it's working now. It definitely wasn't working for a few days when I reported it but I guess can be closed now since it appears to be working. I am using contact.tags.

**Comment by theandrewykim** [comment]
@TLSDwyer Weird! Feel free to re-open if you run into it again.
