### ISSUE TITLE
People data?

### ISSUE THREAD

**Issue by brandoncc** [intercom/intercom-ruby#576]
How do I set people data values using the gem?

```ruby
intercom.contacts.create(
  role: 'lead',
  email: @email,
  'App Environment': Rails.env
)
```

This results in an error that basically says 'App Environment' isn't a method name.

## Version info
  - intercom-ruby version: 4.1.2
  - Ruby version: 2.5.8

**Comment by brandoncc** [comment]
By the way, `App Environment` is a valid people data key that I have setup.

**Comment by theandrewykim** [comment]
Hey @brandoncc  -- to pass in custom attributes(People Data) to Intercom, you'll want to pass in an addition `custom_attributes` hash with any relevant fields. Check out our API docs to check out an example of the JSON body you'd want to mimic. 

https://developers.intercom.com/intercom-api-reference/reference#create-contact


I'll close this one out, but let me know if you run into more problems

**Comment by brandoncc** [comment]
That's exactly what I thought the answer was, unfortunately it didn't work. The people data attribute stays nil.

**Comment by theandrewykim** [comment]
@brandoncc  Can you write into our messenger while logged into Intercom? Our Support Engineer can look at what the request bodies being sent to Intercom look like, and help you troubleshoot

**Comment by brandoncc** [comment]
I'd love to get help by chat. Unfortunately, there is currently a two day wait to get a response by chat (not an exaggeration, that is the actual estimate shown on the chat widget and I've currently been waiting 24 hours for a response to this question on there)...only 24 hours left 👎

**Comment by theandrewykim** [comment]
I hear you on that. Appreciate your patience. Our support team is awesome and doing the best they can.
